### ISSUE TITLE
Not able to control individual volumes of grouped speakers

### ISSUE THREAD

**Issue by uphillbattle** [johanfrick/custom-sonos-card#101]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
5.14.1

**Last working release (if known):**
It’s been like this for a few releases

**Browser and Operating System:**
HA Companion App (latest), iPadOS (16.1.1)

**Description of problem:**
When speakers are grouped and I press the up/down buttons on the right to control the volumes of individual speakers, the individual volume sliders show for half a second or so and then automatically disappears. Consequently, I’m not able to control individual volumes.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by johanfrick** [comment]
Thanks, I can reproduce this. I’ll look into it

**Comment by johanfrick** [comment]
Workaround seems to be to remove progress bar, while I’m looking into it

**Comment by johanfrick** [comment]
Please try the fix above
