### ISSUE TITLE
Pregrouped speaker buttons cause music to stop when used

### ISSUE THREAD

**Issue by chubRock1** [johanfrick/custom-sonos-card#107]
I’m working with the predefined groups and have setup a few (back rooms, downstairs, everywhere) but if I am playing something on say the back rooms and click the button for the predefined group for downstairs, the group gets created but the music stops and I have to start it again. This behavior happens when using any of the predefined groups, but if I have music playing and simply click the individual speaker buttons in grouping they get added or removed from the group and music continues to play. Is there a way to keep the music playing when the predefined groups are used?

I see the same results on several different devices and am running the latest versions of the card and HA.  Let me know how I can help troubleshoot.

**Comment by johanfrick** [comment]
Thanks for the report. I'll add to my list of todos.

**Comment by johanfrick** [comment]
I'm unable to reproduce the bug. Please see the the video. Playing does not stop for me. Can you share a video and explain in more detail how to reproduce the bug?

https://user-images.githubusercontent.com/26582898/211645735-d7317b48-7e6b-48fc-a156-321323dd65c1.mov

**Comment by chubRock1** [comment]
Thanks for the video, I do seem some similar behavior, and it seems that it may have to do with sonos not knowing which speaker should be the control perhaps? If I start playing music on my kitchen speaker, then click my back rooms that seems to work and keeps playing music.  But if I start playing music in the back rooms then click the "downstairs" button it groups the extra speakers but the music stops. 
I have also noticed, that if I start music say on the back rooms group, then click the downstairs group and start the music again it plays, but when I click back to back rooms, the music stays on the speakers that are not the back rooms instead of continuing to play on the back rooms speakers and stopping on the others.  I'll try to grab a video of it.

Here is how I have the grouping setup
type: custom:sonos-grouping
entities:
  - media_player.sonos_move
  - media_player.dining_room
  - media_player.villa
  - media_player.sonos_move_2
  - media_player.kitchen
groupingTitle: ''
predefinedGroups:
  - name: Back Rooms
    entities:
      - media_player.sonos_move
      - media_player.villa
  - name: Downstairs
    entities:
      - media_player.sonos_move
      - media_player.villa
      - media_player.dining_room
      - media_player.sonos_move_2
  - name: Everywhere
    entities:
      - media_player.sonos_move
      - media_player.villa
      - media_player.dining_room
      - media_player.sonos_move_2
      - media_player.kitchen
predefinedGroupsTitle: Quick Groups

**Comment by johanfrick** [comment]
@chubRock1 Can you please try the v5.17.1-beta_preproup?

**Comment by chubRock1** [comment]
Hi, I'm not seeing any real changes to the behavior.  I was beginning to wonder if part of the issue was because I use Amazon Music and only one stream is allow at one time and it seemed like perhaps when it was grouping it was trying to create a second stream, so I also tried playing with Pandora but get the same results.  Here is a screen capture of this test with the beta version.

https://user-images.githubusercontent.com/8963015/212349954-f19695e7-359e-4d29-b5fb-df5cd7f6d9d4.mp4

**Comment by chubRock1** [comment]
Sorry about that last update, I deleted it.  I thought I was on your beta release, but I wasn't.  I just updated correctly to the beta release and it does seem to work correctly now.  Here is a screen clip.  Thanks so much for getting that done so quickly!

https://user-images.githubusercontent.com/8963015/212392003-293840a9-f913-4cb6-8471-f026894881eb.mp4

**Comment by johanfrick** [comment]
That's nice to hear! I got a bit worried there for a minute. I will release it soon to non-beta then
