### ISSUE TITLE
Hide media browser icon in card

### ISSUE THREAD

**Issue by thijselblaso** [johanfrick/custom-sonos-card#108]
I like to have the option to hide the media browser icon or is this already possible?

<img width="530" alt="Screenshot 2023-01-16 at 16 26 21" src="https://user-images.githubusercontent.com/38098396/212715193-a4a48a9e-796f-4550-b338-2da963da5dcc.png">

**Comment by johanfrick** [comment]
Yes, please study the styles/css section in readme.
