### ISSUE TITLE
Recently Played / Audible

### ISSUE THREAD

**Issue by richardwonka** [johanfrick/custom-sonos-card#117]
Since I have the sonos card, the only reason to open the Sonos app is when I want to listen to my audio book(s) via the audible source in Sonos. 

Most commonly, I access it via the “Recently Played” section in the app, which would be very giid to be able to access from Sonos Card, too. 

Alternatively to _Recently Played_ finding the Audible (and other) sources in the media browser would be fantastic. 

🙂👍🏼

**Comment by johanfrick** [comment]
This card relies on the functionality of the [Sonos integration](https://www.home-assistant.io/integrations/sonos), so whatever is supported there is what can be exposed in the card. So with that being said, "recently played" is not something that the integration provides. If you want that, please contact the maintainers of the Sonos integration.
However, if you figure out how to add your audiobook as a favourite in Sonos, then you will see it in this card.
