### ISSUE TITLE
Feature Request: Manual sorting/filtering of favorites list

### ISSUE THREAD

**Issue by rbreneman** [johanfrick/custom-sonos-card#119]
Sonos defaults to sorting the favorites list A-Z and that is how the media browser card displays. Would be awesome if there was a way to manually sort (without a drag/drop option in Sonos app, this would likely be manually entering names into yaml, not ideal but better than nothing) and then control which favorites display and then use multiple media browser cards with custom titles. For example, one card shows radio stations, another card shows my wfie’s favorites, etc…

Summary, 2 asks:

- Manual sort order. Provide via yaml config the order that you want to see favorites displayed
- Ability to show/hide specific favorites by name or the service (Apple Music, Sonos Radio, etc...)

**Comment by johanfrick** [comment]
Thanks, I'll see what I can about this!

**Comment by johanfrick** [comment]
@maddox @rbreneman Please try this beta, and let me know how it works for you:
https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.7-beta1

Example:
<img width="473" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/26582898/de81dfce-4290-4704-9567-d79a03b22e43">


In the visual editor:
<img width="822" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/26582898/b6c1bbfd-f933-4c01-ad9f-3dc378c88109">

In yaml:
```yaml
type: custom:sonos-card
topFavorites: # Show these favorites at the top of the list
  - Legendary
  - Country Rocks
  - Kacey Musgraves Radio
```

README: https://github.com/johanfrick/custom-sonos-card/blob/topFavorites/README.md#configuration-in-yaml

**Comment by maddox** [comment]
WOO! Works great. I know this is a super niche and pedantic request, but it really helps the usability of the playlist picker. Thanks!

**Comment by johanfrick** [comment]
Non-beta released: https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.7

**Comment by maddox** [comment]
i'm seeing weird behavior now where it only lists my playlists from Sonos favorites, and not the stations. I can see the stations in the media browser though.

**Comment by johanfrick** [comment]
I still see stations. Please share your config.

**Comment by maddox** [comment]
```type: custom:sonos-card
entityId: media_player.sonos_family_room
sections:
  - player
  - volumes
  - groups
  - grouping
  - media browser
topFavorites:
  - Chill Station
  - Van Morrison
mediaBrowserShowTitleForThumbnailIcons: false
mediaBrowserItemsPerRow: 1
view_layout:
  grid-area: c2
```

**Comment by maddox** [comment]
This is very odd. I use a custom domain for my hass. When i use that, i don't see stations. When I use the regular IP and Port, i see stations.

I'm also seeing this error in the console:

`Failed to load resource: the server responded with a status of 404 (Not Found)  http://IP:8123/hacsfiles/custom-sonos-card/custom-sonos-card.js.map`

**Comment by maddox** [comment]
I'm also not able to push items to the top that have quotes in them:

`Ollie's List`, `Jon's Rotation`, `Jon Maddox's Station`

Sorry to catch all these AFFFFFFTER the release!

**Comment by johanfrick** [comment]
No worries, nothing is ever bug free right? 😄 
Thanks a lot for testing it so quickly, this made me find another bug also regarding special characters.
Bug fix release is out: https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.7.1
Please test 🙏

**Comment by maddox** [comment]
Looks great! 🎉

**Comment by rbreneman** [comment]
This is great! Would it be possible to have another field that could accept a comma separated list of favorites and a boolean option to show/hide the favorites in that list? Use case would be of my 30+ favorites I only want to make 4 of them available in a specific card on a specific dashboard page (kids room, kitchen, etc...)
