### ISSUE TITLE
Request ability to hide top and bottom banners that obscure cover art.

### ISSUE THREAD

**Issue by billraff** [johanfrick/custom-sonos-card#121]
The ability to view the complete cover art is important to me (and maybe others). Currently often the top and bottom portions of the artwork are obscured by the Top: Title, Artist, Album name and Bottom: all the controls. I would like it if there were a flag to enable those banners to disappear until a mouse over event. In other words I would see -

<img width="490" alt="Screenshot 2023-03-24 at 7 03 49 AM" src="https://user-images.githubusercontent.com/29167787/227517204-fe3d0d9c-4bef-4fa8-b257-56876dcbddbd.png">
 rather than -

<img width="677" alt="Screenshot 2023-03-24 at 7 00 06 AM" src="https://user-images.githubusercontent.com/29167787/227517290-449129ac-f83b-4347-a415-cc31313c44c9.png">

If I needed to see the Top or Bottom features I could mouse over them.

**Comment by johanfrick** [comment]
Thanks, I'll add this to the list of Todo:s

**Comment by johanfrick** [comment]
Is this still relevant after the release of v6?
