### ISSUE TITLE
Set size of individual card (player)

### ISSUE THREAD

**Issue by Symbiot78** [johanfrick/custom-sonos-card#125]
Hey

I have a 1 column layout where I have a vertical stack with player & browser.
on mobile it looks great but on a bigger screen the player becomes massive.

can I set the size of the player and differentiate between mobile & laptop for instance? and how :)

**Comment by johanfrick** [comment]
Either create different dashboards for mobile and desktop, or use a dynamic layout with for instance https://github.com/thomasloven/lovelace-layout-card
