### ISSUE TITLE
Media Browser with icons only

### ISSUE THREAD

**Issue by z06Drew** [johanfrick/custom-sonos-card#128]
The Media Browser is always displaying my favorites as a list with a small thumbnail to the left of the name.  I'm wanting only the icons displayed in a grid.  I've tried omitting mediaBrowserItemsAsList: as well as mediaBrowserItemsAsList: false with no success.  I've tried with the simplest default configuration using only type: custom:sonos-card as well as individual cards for each section with the same results.  I'm running the lastest 2023.6.1

**Comment by johanfrick** [comment]
That feature is not there in v6 I am afraid. It was quite complex to maintain. I'll consider implementing it again. 
For now, you can downgrade to an earlier version of the card (before v6).

**Comment by z06Drew** [comment]
Thanks for the quick response.  It would be great to have it, I love the new look and feel, much better consistency with the rest of HA cards but I must admit that at least IMO the list view for the favorites ends up wasting a lot of space.  You may want to remove reference to the mediaBrowserItemsAsList: option in the new ReadMe file since it's not intended to work anymore.  As a dev manager myself, I appreciate the need to prioritize features and that this is "free software" that you are sharing with the community.  Thanks again for the response and the update, I like it a lot!

**Comment by johanfrick** [comment]
Thanks for spotting that! I've removed it now 🙏

**Comment by johanfrick** [comment]
Converted this to a feature request

**Comment by RaoulV82** [comment]
+1 on this. Again awesome card. Eager to use the new functionality as looks very slick, but will stick to the previous version to maintain the artwork only media selection. Looking. Forward to seeing how the card progresses.

**Comment by nbanbury** [comment]
I love this card and the update is really nice. I too would very much like to be able to show Media Browser as icons only so just adding a +1 :)

**Comment by johanfrick** [comment]
@nbanbury @RaoulV82 @z06Drew Please try out this beta https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.5.0-beta1
Use mediaBrowserItemsPerRow > 1 to enable. E.g.
```
type: custom:sonos-card
mediaBrowserItemsPerRow: 4
```
Let me know if it is working fine for you.

**Comment by RaoulV82** [comment]
Great news! Will try this weekend and update. Thanks again.

**Comment by nbanbury** [comment]
Amazing! Will test now and report back. Thanks

**Comment by nbanbury** [comment]
Perfectly, very elegant solution. Thank you.

**Comment by IzeQube** [comment]
Wow, this is looking really good. Any chance to get the title on top of the playlists or radio stations?

**Comment by z06Drew** [comment]
Perfect!, just what I was looking for.  Looks and works great!  Thank you

![image](https://github.com/johanfrick/custom-sonos-card/assets/116745919/d5f7a9ae-3b9a-4382-9791-25a9d80a9bbb)

**Comment by johanfrick** [comment]
Released! https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.5.0
@IzeQube Use `mediaBrowserShowTitleForThumbnailIcons` to get the titles for artwork as well
