### ISSUE TITLE
i.setConfig is not a function on HA 2023.6.1 with version v6

### ISSUE THREAD

**Issue by gedl** [johanfrick/custom-sonos-card#129]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
v6 on HA version 2023.6.1
**Last working release (if known):**

**Browser and Operating System:**
Chrome 113.0.5672.126 on macOS Ventura

**Description of problem:**

custom:sonos-media-browser displays i.SetConfig is not a function error message.

**Javascript errors shown in the web inspector (if applicable):**

```
create-element-base.ts:182 card custom:sonos-media-browser TypeError: i.setConfig is not a function
    at r (create-element-base.ts:97:11)
    at create-element-base.ts:111:12
    at h (create-element-base.ts:215:12)
    at c (create-element-base.ts:172:12)
    at k (create-card-element.ts:98:3)
    at i.value (hui-view.ts:64:21)
    at i.value (hui-view.ts:299:26)
    at t.addEventListener.once (hui-view.ts:78:16)
    at r (fire_event.ts:76:8)
    at create-element-base.ts:129:5
```

**Additional information:**
1 - Installed through HACS version 1.32.1

2 - Dashboard code looks like the below:

```title: Testing
views:
  - path: default_view
    title: Home
    badges: []
    cards:
      - type: custom:sonos-card
      - type: custom:sonos-media-browser
        mediaTitle: ''
```

3 - The `custom:sonos-card` card loads OK but `custom:sonos-player` does not (same error occurs)

**Comment by johanfrick** [comment]
Unfortunately with the new version (v6) it is not possible to use anything else than `custom:sonos-card`. 
Use the `sections` configuration to select a specific section
<img width="974" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/26582898/f7a57ff9-0252-44b2-84f5-5941d55d24f7">

or in YAML:
```
type: custom:sonos-card
sections:
  - media browser
```

**Comment by gedl** [comment]
Is it possible at all to add shortcuts to specific media sources, like a specific radio station?

**Comment by johanfrick** [comment]
Check out customSources in the documentation: https://github.com/johanfrick/custom-sonos-card#configuration-in-yaml

**Comment by gedl** [comment]
👍  got it. thanks
