### ISSUE TITLE
Next on Spotify playlist or own media

### ISSUE THREAD

**Issue by fantastrick** [johanfrick/custom-sonos-card#130]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Release with the issue:**
latest

**Last working release (if known):**
last release

**Browser and Operating System:**
HA runs on Raspberry Pi

**Description of problem:**
It seems like when I start a playlist in Spotify in the Sonos app the Next and Previous button don't work. The same happens with own media files. There is no possibility to skip forward or back. In the Sonos favorites it does work.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by johanfrick** [comment]
I tried this on my own setup with Spotify playlist from Sonos app. I was able to skip forward and back with the card.

**Comment by fantastrick** [comment]
Hi! Thanks for the reply :)
I was using the playlists from the Spotify integration, not those in the Spotify favorites. That can be the difference.

Rick


Op 12 jun. 2023, om 20:50 heeft Johan Frick ***@***.***> het volgende geschreven:



I tried this on my own setup with Spotify playlist from Sonos app. I was able to skip forward and back with the card.

**Comment by fantastrick** [comment]
Forgot to add, also when using local media from the storage it doesn’t skip.

Op 12 jun. 2023, om 21:21 heeft Rick Schouten ***@***.***> het volgende geschreven:

Hi! Thanks for the reply :)
I was using the playlists from the Spotify integration, not those in the Spotify favorites. That can be the difference.

Rick


Op 12 jun. 2023, om 20:50 heeft Johan Frick ***@***.***> het volgende geschreven:



I tried this on my own setup with Spotify playlist from Sonos app. I was able to skip forward and back with the card.

**Comment by johanfrick** [comment]
I am still not able to reproduce the behaviour you explain I am afraid.

**Comment by johanfrick** [comment]
Cannot reproduce this. Let me know if you have any suggestions on how to.
