### ISSUE TITLE
Spotify playlists stoped showing

### ISSUE THREAD

**Issue by reimersa74** [johanfrick/custom-sonos-card#131]
**Checklist:**

- [ x] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
v6
**Last working release (if known):**

**Browser and Operating System:**

Windows 11. Latest Official Homeassitant, Chrome, Edge, Android tablet

**Description of problem:**
Suddenly Spotify playlists wont show. 

![image](https://github.com/johanfrick/custom-sonos-card/assets/78260245/3c94a86b-bec0-4a3a-aa01-a960974f8bf7)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by reimersa74** [comment]
Get this error in log when trying to open playlist
![image](https://github.com/johanfrick/custom-sonos-card/assets/78260245/077dffb8-0207-49f8-bced-b059610e08f0)

**Comment by reimersa74** [comment]
As of now 2023-06-11 22:08 it suddenly started to work again... Hmmm

**Comment by johanfrick** [comment]
Ok, let's close it for now as I've not heard anyone else report it. We can reopen if it reoccurs.
