### ISSUE TITLE
Home Assistant 2023.6.2 throws resources error

### ISSUE THREAD

**Issue by cralwalker** [johanfrick/custom-sonos-card#135]
**Checklist:**

- [v] I updated to the latest version available
- [v] I cleared the cache of my browser

**Release with the issue:**
Home Assistant 2023.6.2
**Last working release (if known):**
Home Assistant 2023.5
**Browser and Operating System:**

 Brave on Mac, [Version 1.51.118 Chromium: 113.0.5672.126 (Official Build) (x86_64)](https://brave.com/latest/)
MacOS Ventura 13.4

**Description of problem:**

 This morning: Home Assistant 2023.6.2 throws resources error, 'Integration error: resources - Integration 'resources' not found.'

configuration.yaml entry:
#Sonos card
resources:
  - url: /local/custom-sonos-card.js?v=1.0
    type: module

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest

**Comment by johanfrick** [comment]
Working and non working versions should be for the card. Can you please provide that?

**Comment by johanfrick** [comment]
Cannot reproduce this. Let me know if you have any suggestions on how to.
