### ISSUE TITLE
Live editor not showing

### ISSUE THREAD

**Issue by grahamhealy20** [johanfrick/custom-sonos-card#136]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
V6

**Last working release (if known):**

**Browser and Operating System:**
Windows 11 + Chrome. Also tried with mobile app on iOS 16.

**Description of problem:**
Hi, it seems that the Visual Editor isn't working for me. I tried V6 + latest master and it seems to persist. There is a JS error that is thrown when I press edit on the card.

![image](https://github.com/johanfrick/custom-sonos-card/assets/10790901/6a8beaaa-a196-4bc0-b567-8688d9095c6a)

**Javascript errors shown in the web inspector (if applicable):**

```
custom-sonos-card.js?hacstag=4494168166:228 Uncaught (in promise) TypeError: Cannot add property sections, object is not extensible
    at pt.render (custom-sonos-card.js?hacstag=4494168166:228:685)
    at pt.update (custom-sonos-card.js?hacstag=4494168166:23:292)
    at pt.performUpdate (custom-sonos-card.js?hacstag=4494168166:11:5085)
    at pt.scheduleUpdate (custom-sonos-card.js?hacstag=4494168166:11:4732)
    at pt._$Ej (custom-sonos-card.js?hacstag=4494168166:11:4640)
```

**Additional information:**
Thank you very much for your hard work on this custom component, it's amazing!

**Comment by johanfrick** [comment]
Which version of Home Assistant?

**Comment by grahamhealy20** [comment]
Hi Johan, it's 2023.6.2

**Comment by johanfrick** [comment]
Thanks for reporting this bug! It should now be fixed in v.6.2.2.

**Comment by grahamhealy20** [comment]
Thanks so much for your work on this Johan! 🥇
