### ISSUE TITLE
Chips layout for grouping card

### ISSUE THREAD

**Issue by mikedrawback** [johanfrick/custom-sonos-card#138]
I really liked the 'chips' layout instead of the checkbox list for the old grouping card. It was very compact and fit well in my small dashboard. Can an option for that be added back? Otherwise I love the new cards, thanks for making this!!

**Comment by johanfrick** [comment]
Thanks for your feedback, I'll take it into consideration once I have addressed all reported bugs.

**Comment by johanfrick** [comment]
Had a look at this, and I probably won't do it anytime soon. Will be too big of a job to develop and maintain both versions. I'll close it for now, but anyone who is up for contributing is welcome, if so we'll just reopen this issue.
