### ISSUE TITLE
Please add back Volume up and Volume down step buttons

### ISSUE THREAD

**Issue by usingapc** [johanfrick/custom-sonos-card#139]
With the new Sonos Card, incremental Volume Up/Down step buttons are no longer available on the card.  This causes several issues.  The first is that if I have 2 different kinds of speakers linked together(like Arc and portable Roam speakers) they have very different db levels at the same volume setting.  In the old card I was able to set more powerful speakers like the Arc to a lower volume and then the roam speakers at a higher volume to balance the sound level in different rooms.  When step increasing or decreasing volume, it kept a fairly consistent listening level in the multiple rooms.  With the new card, adjusting the volume slider on the home card adjusts all speakers to the same % level.  I can't find a way to increase the speakers by the same number of steps like the old card.  When multiple speakers are linked it becomes really hard to keep volume levels consistent across the different rooms with different types of speakers.

Please add back Volume up and down buttons on the main card.  It would also be nice to add them to the speaker(s) volume tab as well.

**Comment by johanfrick** [comment]
Makes sense, I'll look into this.

**Comment by johanfrick** [comment]
Included in v6.3. You have to enable it in configuration.
