### ISSUE TITLE
Clearly mark multiple TV inputs (as in the sonos app)

### ISSUE THREAD

**Issue by gdgib** [johanfrick/custom-sonos-card#145]
**Is your feature request related to a problem? Please describe.**
In systems with more than 1 device with a TV or Line-In, the sonos card does not recognize that these are different sources.  As such one cannot properly select the correct TV input on the favorites tab.

**Describe the solution you'd like**
When there are multiple TV or Line-In inputs, they should be separated, and clearly labeled as in the sonos app.  For example "TV: Family Room" and "TV: Living Room".

**Describe alternatives you've considered**
1. Use the sonos app
2. Use other UI cards
3. Create a second level of selection wherein one selects "TV" and then is shown multiple TV inputs.

**Additional context**
I will take a stab at coding this myself.  I'm opening the issue so that others are aware of it, but I fully expect to implement this if I can.

**Comment by gdgib** [comment]
I'm about 90% sure the logic on https://github.com/johanfrick/custom-sonos-card/blob/master/src/services/media-browse-service.ts#L46 has an annoying feature/bug.  Once the user marks some media as a favorite, it will no longer show the `source_list` in favorites, meaning if you have any favorite you won't see TV inputs.

As for the actual feature, it's https://github.com/johanfrick/custom-sonos-card/blob/master/src/services/media-browse-service.ts#L69 that needs to be changed.  The `Set` construction is removing duplicates, whereas we should be labeling them.  Reproducing the logic of the sonos app will require a detecting which sources have duplicates (a simple pop count dictionary) followed by a re-naming (can be a map).  There is no non-stateful way to replicate the sonos app, the only alternative is that I just label *every* source with the device it's coming from.

**Comment by gdgib** [comment]
Hey @johanfrick any advice on setting up a development environment for this?  I haven't developed a UI component for HA/HACS before.  Obviously you use vscode & node, but a specific node version would be helpful to know, and any suggestions you have on how to set up a decent modify-compile-test loop.

Definitely not required.  But I'd be silly not to ask.

**Comment by johanfrick** [comment]
Good question! I detailed my setup as a Q&A now: https://github.com/johanfrick/custom-sonos-card/discussions/147

**Comment by gdgib** [comment]
I was thinking about changing https://github.com/johanfrick/custom-sonos-card/blob/5b86222a83ce018fca18f3cb190a4a4ffbe6605e/src/sections/media-browser.ts#L149 to select the source on the correct player, but since the groups tab is used to select a group, I'm not really sure how one could select the TV input of anything except the primary player in the current group (`this.entityId`).

A few options:

1. Convert the TV input favorite a JSON object having both the entity ID of the player and the title "TV".  Then when playing the item, select the source on the correct entity.  I'm not sure this will work to set the whole group, but it's worth a try.
2. Same as above, but also change `this.entityId` when selecting the TV source if it comes from a player other than `this.entityId`.
3. Change https://github.com/johanfrick/custom-sonos-card/blob/5b86222a83ce018fca18f3cb190a4a4ffbe6605e/src/sections/media-browser.ts#L154 to only show favorites from states from `this.entityId`

I'm leaning toward 1 or 2, which more closely match the behavior of the Sonos app.  3 is a fallback, which would require the user to deliberately re-group players when they have two players with TV inputs in a group and want to set them both to play the same TV input.

(BTW, I'm just writing design notes as I do for now, feedback on the feature is welcome)

**Comment by johanfrick** [comment]
Yes, 1&2 sound good

**Comment by gdgib** [comment]
Yeah, it's on my personal issue tracker, so it won't get lost. Feel free to close it if you prefer, I can open another issue when I get the time.

**Comment by johanfrick** [comment]
Sounds good. No worries, let's keep this issue 😄

**Comment by johanfrick** [comment]
I'm gonna close this one for now, let me know when you have something ready and we'll reopen the issue.
