### ISSUE TITLE
artwork size

### ISSUE THREAD

**Issue by Vansmak** [johanfrick/custom-sonos-card#149]
Just did an update and I like the changes as it's similar to the way I was laying it out using tabbed card. However, I miss the larger artwork, not just a small thumbnail?

**Comment by johanfrick** [comment]
I'll see if I can make this customisable

**Comment by Vansmak** [comment]
No worries, I went back to mini-media-player

**Comment by timvdsm** [comment]
> No worries, I went back to mini-media-player ![Screenshot_20230802_180252_Home Assistant.jpg](https://user-images.githubusercontent.com/16037573/257973481-a72600e9-b98c-43d6-b0f5-a500746e6813.jpg)![Screenshot_20230802_180246_Home Assistant.jpg](https://user-images.githubusercontent.com/16037573/257973491-f38c0baa-d682-4055-b51a-aa25a39316ac.jpg)

Willing to share your code?
