### ISSUE TITLE
Adding a title doesn't increase subframe height so you get a scroll bar

### ISSUE THREAD

**Issue by robchandhok** [johanfrick/custom-sonos-card#150]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
6.3
**Last working release (if known):**

**Browser and Operating System:**
Chrome 115.0.5790.56/MacOS

Same behavior on iOS/HA app

**Description of problem:**
If you add the optional "title", you get a scroll bar for the part of the player card above the buttons, so the volume level appears clipped (but is really just scrollable)

IMHO the height is calculated the same regardless of if the title text is present.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
<img width="516" alt="Screenshot 2023-07-04 at 11 52 20 AM" src="https://github.com/johanfrick/custom-sonos-card/assets/10090570/7ee14b56-e676-4c7b-889c-f37af65ab894">

**Comment by johanfrick** [comment]
Thanks for reporting

**Comment by NR3Y** [comment]
I can confirm these symptoms. I am seeing it on Safari, Home Assistant application (for MacOS) and my iPad.

**Comment by johanfrick** [comment]
Fixed in [v6.4.1](https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.4.1)
