### ISSUE TITLE
Allow bigger card width

### ISSUE THREAD

**Issue by MaximilianoFelice** [johanfrick/custom-sonos-card#151]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to have cards of bigger width than 40rem.

Limits are imposed by this function: https://github.com/johanfrick/custom-sonos-card/blob/db58bfc91920335206f201c187d68db9360d9715/src/card.ts#L223C18-L223C18

**Describe the solution you'd like**
Card width should self-ajdust to container, keeping elements centered

**Describe alternatives you've considered**
- Letting us manually override the max-width with >100 `maxWidth` config option, which is currently restricted.

**Additional context**
Current behaviour leads to really unaesthetic dashboards:

<img width="715" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/5333485/5259dc04-ee33-4f22-9c67-4893b798b5e4">

**Comment by johanfrick** [comment]
Thanks!
I'll add this to my todo list. Feel free to make a PR if you want it done sooner.

**Comment by johanfrick** [comment]
Fixed in [v6.4.1](https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.4.1)
