### ISSUE TITLE
using the selected speaker in a button card.

### ISSUE THREAD

**Issue by misterwesley** [johanfrick/custom-sonos-card#153]
Is it possible to use the selected speaker in a button card to call a service?
I use buttons to play media to a speaker which is selected in a input select helper. This is because the media browser show's everything and I only want certain media to play.
I'm kinda hoping to make my dashboard not have 2 select speaker cards. 

Example of button:
      - type: custom:button-card
        entity: input_select.welke_speaker
        show_entity_picture: true
        entity_picture: /local/img/SLAM_.jpg
        styles:
          entity_picture:
            - width: 150px
            - height: 150px
        show_state: false
        show_name: false
        tap_action:
          action: call-service
          service: media_player.play_media
          service_data:
            media_content_id: media-source://radio_browser/962e7e22-0601-11e8-ae97-52543be04c81
            media_content_type: audio/mpeg
            entity_id: '[[[ return states["input_select.welke_speaker"].state ]]]'

**Comment by johanfrick** [comment]
This sounds like something you should ask in the github repo for custom:button-card?
