### ISSUE TITLE
Album Year

### ISSUE THREAD

**Issue by lk229** [johanfrick/custom-sonos-card#157]
Would it be possible to add the album year to the information displayed? If it matters, I mostly use the YouTube Music service provider.

**Comment by johanfrick** [comment]
I'll take a look

**Comment by johanfrick** [comment]
I can't see that year is available in Home Assistant's Sonos integration. See example below. Feel free to reopen issue if you have any idea on how to get the year.
<img width="1445" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/26582898/d4ad0e4d-60cf-4f39-9a9f-8d72d4d59719">
