### ISSUE TITLE
No Volume Slider 

### ISSUE THREAD

**Issue by Stephan1908** [johanfrick/custom-sonos-card#159]
Hello,
I have the latest version 6.3 installed,
I cleared the browser cache and reloaded the browser.
But I don't get the volume slider displayed:

![grafik](https://github.com/johanfrick/custom-sonos-card/assets/60405276/d883e5ae-1f7a-45ac-9a8d-a049b5fd9e43)

Not even in the groups.

Does anyone have any idea why this might be?
Thank you very much

Greetings Stephan

**Comment by Stephan1908** [comment]
Hey, 
that's the problem then.  I have installed 2023.1.1, currently have no time to update.  Is it possible to install an older version?  The sliders were still working.  
Greetings Stephen

**Comment by johanfrick** [comment]
Sure, anything below version 6 should work

**Comment by Stephan1908** [comment]
Hi,
how can i do a downgrade? in hacs i only get the versions from 6 displayed.
![grafik](https://github.com/johanfrick/custom-sonos-card/assets/60405276/2b7ba938-d2dc-4294-bebb-0e1c3f276bc1)

**Comment by johanfrick** [comment]
Don't know. You should ask in HACS forum
