### ISSUE TITLE
Speaker playing indicator isn't working properly

### ISSUE THREAD

**Issue by usingapc** [johanfrick/custom-sonos-card#160]
**Release with the issue:**
6.4.1

**Last working release (if known):**
not sure what I upgrade from.

**Browser and Operating System:**
Web browser, android ha app, and ios ha app

**Description of problem:**
On the speaker selection/groups section the indicator that shows if it is playing is only showing as a small dot. 
![sonos card screen shot](https://github.com/johanfrick/custom-sonos-card/assets/90284468/5bc9a1b7-a06b-44d5-a805-14c29a8f706b)

In prior releases it showed a bar graph(I believe even animated but can't remember) to indicate that it was playing music.

**Comment by johanfrick** [comment]
Thanks for reporting! I'll look into it
