### ISSUE TITLE
support  for template in entity name

### ISSUE THREAD

**Issue by tortho** [johanfrick/custom-sonos-card#161]
Feature request to be able to automate music following me around the house and then easily select media to this "group" 
Using this approach to auto group/ungroup speakers: https://community.home-assistant.io/t/group-sonos-and-ungroup-sonos-based-on-presence-scripts-automations/298015

Would like to define the entity as:
entityId: media_player.{{ states('input_select.sonos_music_master_speaker') }}

media_player.{{ states('input_select.sonos_music_master_speaker') }} in my case might for instance result in media_player.move_kontor which is one of the sonos speakers

At present when using template it just picks the first sonos in the list and further it does not show already grouped sonos which then results in a lot of clicking to group them all.

**Comment by johanfrick** [comment]
@tortho Please have a go at this beta and see if it works for you: [v6.8-beta1](https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.8-beta1)
Example: 
```
type: custom:sonos-card
entityId: media_player.{{ states('input_select.sonos_music_master_speaker') }}
```

**Comment by tortho** [comment]
This is really excellent news and great work!!!
Downloaded and works perfect so far :-)

Then I can remove my dashboard with xx number of players which will be hidden/shown conditionally and just use 1 card :-)

**Comment by johanfrick** [comment]
Thanks! Happy you like it 😄

**Comment by tortho** [comment]
1 comment, it seem like the card constantly "reloads", by that I mean,

If I have the card open and goes to favorites which is a scrollable list and scrolls down it takes just a second and I'm on top of the list again.
Scrolling down it jumps to the top of the list again.
(Same goes for the other lists of speakers also - I have quite a few :-)

**Comment by johanfrick** [comment]
Ouch. thanks for finding that. Reverting v6.10 for now.

**Comment by johanfrick** [comment]
I can't reproduce this, not sure how to go forward. Are you able to do some debugging in Chrome Dev Tools to see why this happens? Or if you have any suggestions for how to make it happen when I try it.

**Comment by misterwesley** [comment]
Is it also possible that the card writes the value to an input select based on the selected speaker?
This is so I can create a custom button to play a certain playlist that is currently selected.

Alternativly maybe a media browser where I can select only certain playlists. With all radio stations from radio browser and a lot of media it's a lot of playlists.

**Comment by johanfrick** [comment]
Did you find time to debug the constant reload?
