### ISSUE TITLE
Error : i.setConfig is not a function

### ISSUE THREAD

**Issue by LNMGG** [johanfrick/custom-sonos-card#166]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue: 6.5.0 you just released but also the one before

**Last working release (if known): not try

**Browser and Operating System: Client : Safari iOS up to date Server : Docker with HA up to date

**Description of problem: I have a new HA installation working on docker
I try tou add your great custom sonos card
The main card type: custom:sonos-card work perfect

But I have an error with all other one 

The error is the card is the following : i.setConfig is not a function. (In 'i.setConfig(t)', 'i.setConfig' is undefined)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by johanfrick** [comment]
custom:sonos-card is the only one you can use. You can configure it to show individual sections. Make sure you read through the documentation.

**Comment by LNMGG** [comment]
Ok i see, but it is strange to add others type in the card selection page UI if they doesn't exist no ?

**Comment by johanfrick** [comment]
Not sure what you mean by that

**Comment by STRML** [comment]
I think he means this:

<img width="966" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/1197375/c8211958-5459-430a-9c2d-42a39c894043">

When you actually select any of these, other than the first one, it will crash instead.

**Comment by LNMGG** [comment]
exactly

**Comment by johanfrick** [comment]
Wow, I was sure I had already removed those. Thanks for reporting 🙏  @LNMGG @STRML 
It's now fixed in https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.13.2
