### ISSUE TITLE
volumeslider | disable/enable or customize

### ISSUE THREAD

**Issue by Symbiot78** [johanfrick/custom-sonos-card#168]
is it possible to either disable the volume slider or at least change it a bit. on my layout it takes up quite a lot of space.

i'd like the option to only have the up down buttons or edit the size.

**Comment by johanfrick** [comment]
You'd need https://github.com/thomasloven/lovelace-card-mod for that. Then do:
```
type: custom:sonos-card
card_mod:
  style:
    sonos-player$ sonos-player-controls$: |
      sonos-volume {
        display: none;
      }
```
