### ISSUE TITLE
Card is not showing when one speaker is offline

### ISSUE THREAD

**Issue by micgit3** [johanfrick/custom-sonos-card#17]
**Checklist:**

- [ X] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
none

**Browser and Operating System:**

Hassio Supervisor on RPI4 / Edge Browser

**Description of problem:**

see above, ggod to know , if i change the name of the unavailable speaker to something not registered in HA, the Sonos Card shows up as it should

**Javascript errors shown in the web inspector (if applicable):**
![Screenshot 2022-02-22 105849](https://user-images.githubusercontent.com/97024916/155108682-c8093ec6-db00-4fcd-a27a-7442724f675e.png)
![Screenshot 2022-02-22 105820](https://user-images.githubusercontent.com/97024916/155108684-b8171f0f-5655-4038-a0e8-dd6758644ed0.png)

59custom-sonos-card.js?hacstag=449416816210:463 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at :8123/hacsfiles/custom-sonos-card/custom-sonos-card.js?hacstag=449416816210:463:532
    at Array.filter (<anonymous>)
    at ct.createPlayerGroups (:8123/hacsfiles/custom-sonos-card/custom-sonos-card.js?hacstag=449416816210:463:465)
    at ct.render (:8123/hacsfiles/custom-sonos-card/custom-sonos-card.js?hacstag=449416816210:408:649)
    at ct.update (:8123/hacsfiles/custom-sonos-card/custom-sonos-card.js?hacstag=449416816210:37:405)
    at ct.performUpdate (:8123/hacsfiles/custom-sonos-card/custom-sonos-card.js?hacstag=449416816210:25:5057)
    at ct.scheduleUpdate (:8123/hacsfiles/custom-sonos-card/custom-sonos-card.js?hacstag=449416816210:25:4704)
    at ct._$E_ (:8123/hacsfiles/custom-sonos-card/custom-sonos-card.js?hacstag=449416816210:25:4612)
custom-sonos-card.js?hacstag=449416816210:25 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at custom-sonos-card.js?hacstag=449416816210:463:532
    at Array.filter (<anonymous>)
    at ct.createPlayerGroups (custom-sonos-card.js?hacstag=449416816210:463:465)
    at ct.render (custom-sonos-card.js?hacstag=449416816210:408:649)
    at ct.update (custom-sonos-card.js?hacstag=449416816210:37:405)
    at ct.performUpdate (custom-sonos-card.js?hacstag=449416816210:25:5057)
    at ct.scheduleUpdate (custom-sonos-card.js?hacstag=449416816210:25:4704)
    at ct._$E_ (custom-sonos-card.js?hacstag=449416816210:25:4612)
_$E_ @ custom-sonos-card.js?hacstag=449416816210:25
await in _$E_ (asynchron)
requestUpdate @ custom-sonos-card.js?hacstag=449416816210:25
set @ custom-sonos-card.js?hacstag=449416816210:25
(anonym) @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
value @ hui-root.ts:500
_$AE @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
k @ styles.ts:368
_$AI @ styles.ts:368
m @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
value @ app-drawer-layout.js:189
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
k @ styles.ts:368
_$AI @ styles.ts:368
m @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
k @ styles.ts:368
_$AI @ styles.ts:368
m @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
value @ styles.ts:368
(anonym) @ styles.ts:368
s @ core.30819411.js:1
(anonym) @ core.30819411.js:1
(anonym) @ core.30819411.js:1
_handleMessage @ core.30819411.js:1
25custom-sonos-card.js?hacstag=449416816210:463 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at custom-sonos-card.js?hacstag=449416816210:463:532
    at Array.filter (<anonymous>)
    at ct.createPlayerGroups (custom-sonos-card.js?hacstag=449416816210:463:465)
    at ct.render (custom-sonos-card.js?hacstag=449416816210:408:649)
    at ct.update (custom-sonos-card.js?hacstag=449416816210:37:405)
    at ct.performUpdate (custom-sonos-card.js?hacstag=449416816210:25:5057)
    at ct.scheduleUpdate (custom-sonos-card.js?hacstag=449416816210:25:4704)
    at ct._$E_ (custom-sonos-card.js?hacstag=449416816210:25:4612)
(anonym) @ custom-sonos-card.js?hacstag=449416816210:463
createPlayerGroups @ custom-sonos-card.js?hacstag=449416816210:463
render @ custom-sonos-card.js?hacstag=449416816210:408
update @ custom-sonos-card.js?hacstag=449416816210:37
performUpdate @ custom-sonos-card.js?hacstag=449416816210:25
scheduleUpdate @ custom-sonos-card.js?hacstag=449416816210:25
_$E_ @ custom-sonos-card.js?hacstag=449416816210:25
await in _$E_ (asynchron)
requestUpdate @ custom-sonos-card.js?hacstag=449416816210:25
set @ custom-sonos-card.js?hacstag=449416816210:25
(anonym) @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
value @ hui-root.ts:500
_$AE @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
k @ styles.ts:368
_$AI @ styles.ts:368
m @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
value @ app-drawer-layout.js:189
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
k @ styles.ts:368
_$AI @ styles.ts:368
m @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
k @ styles.ts:368
_$AI @ styles.ts:368
m @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (asynchron)
requestUpdate @ styles.ts:368
set @ styles.ts:368
value @ styles.ts:368
(anonym) @ styles.ts:368
s @ core.30819411.js:1
(anonym) @ core.30819411.js:1
(anonym) @ core.30819411.js:1
_handleMessage @ core.30819411.js:1
```

```

**Additional information:**

**Comment by johanfrick** [comment]
@micgit3 Thanks for the detailed report.
Could you please try this beta? https://github.com/johanfrick/custom-sonos-card/releases/tag/v2.2.1-beta

I am not sure I solved it, but I tried to add some debugging when it crashes. So if it doesn't work, please check output in console.

**Comment by micgit3** [comment]
The 2.2.1 was the same error, but now installed the 2.3.0,. And I see my Sonos, thx for that
But I don't see favourites anymore.

**Comment by micgit3** [comment]
![Screenshot_20220222-220510_Home Assistant](https://user-images.githubusercontent.com/97024916/155219279-f552f806-9c90-4427-bb0e-54e9eab4367a.jpg)

**Comment by micgit3** [comment]
Ok, found the error, I deleted the "entities" and the Favorites show up

**Comment by johanfrick** [comment]
Ok, I've released a fallback to skip the images: v2.3.1.
I'll close the issue, but let me know if you still have problems.
