### ISSUE TITLE
Font colour on media browser icons

### ISSUE THREAD

**Issue by walts22** [johanfrick/custom-sonos-card#170]
Hi,

I am trying to see where the font colour is selected for the playlist titles. 

As shown in this screenshot mine is white/light grey in which I can't see the playlist title:
![image](https://github.com/johanfrick/custom-sonos-card/assets/87230803/914e61f1-bcf3-4950-ace7-44e8bc28dcfd)
(most of my playlist titles are less obvious than these ones)

My card config:

    type: custom:sonos-card
    sections:
      - media browser
    showVolumeUpAndDownButtons: false
    mediaBrowserTitlesToIgnore: My media Favorites Music Library
    widthPercentage: 106
    heightPercentage: 117
    mediaBrowserItemsPerRow: 3
    mediaBrowserShowTitleForThumbnailIcons: true
    
 Current view theme is IOS dark mode dark green and the main theme including fonts is Kibibit. 
 I have tried with a few different themes with the same result. 
 
 Any suggestions on how to change this font colour would be greatly appreciated.

**Comment by johanfrick** [comment]
Thanks for the bug report! Release out with the fix: https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.5.1

**Comment by walts22** [comment]
> Thanks for the bug report! Release out with the fix: https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.5.1

Thank you so much for the quick fix!!

**Comment by walts22** [comment]
Hi there, Johan.

When you get a chance, can you see if this has been changed back in the latest 6.10.1 version.

My titles have gone back white again. (could be just me as I've migrated to a new HA server)

**Comment by johanfrick** [comment]
I can't reproduce that. You can select version with hacs and try the different versions. Please do that and see if it behaves differently for different versions.

**Comment by walts22** [comment]
> I can't reproduce that. You can select version with hacs and try the different versions. Please do that and see if it behaves differently for different versions.

Thanks Johan.
I just had a play. And it's fine for any of the ios-light themes, but for the dark themes the text goes super light.

I will try and roll back to an older version now to see if that works.
