### ISSUE TITLE
call sonos groups and grouping from scripts

### ISSUE THREAD

**Issue by robertw** [johanfrick/custom-sonos-card#177]
simply the card is very cool and now since vol grouping are saved in one place the ablity to make a call to trigger the group and auto play with vol would be wonderfull or maybe we can and i am missing some thing 
 one last point also muting shoukld be turned off when a group is selected as a option

...thank you

**Comment by johanfrick** [comment]
I'm afraid making a call to a function here is not possible since there is no backend part for this card.
Regarding muting, that is already supported with 'unmuteWhenGrouped'.
