### ISSUE TITLE
MediaCard is too small in browser

### ISSUE THREAD

**Issue by r100gs** [johanfrick/custom-sonos-card#18]
Hello,

I love the design of this card, but on my browser (vivaldi, latest version) the mediacard seems to small.
Please see attached picture

I use the latest version on HA 2022.2.9

In android app it looks fine.

Best regards and thx for this card.

![image](https://user-images.githubusercontent.com/12609988/155315558-987ce4dc-acb4-4383-a89a-d9ca445c523e.png)

![image](https://user-images.githubusercontent.com/12609988/155315787-f585448e-6cce-4e90-bf11-69f4099536dd.png)

**Comment by johanfrick** [comment]
Fixed by https://github.com/johanfrick/custom-sonos-card/commit/5ffe1a484eebc7634cdff751aba40e52b9a83326
