### ISSUE TITLE
Add the ability to allow all playlists to have a shuffle button when selected

### ISSUE THREAD

**Issue by finder39** [johanfrick/custom-sonos-card#180]
**Is your feature request related to a problem? Please describe.**
A lot of the time when I want to play a (Spotify) playlist I want to shuffle it to ensure I'm not always hearing the same songs. To do this currently via the Sonos Card, I have to select the playlist from favorites (or from spotify->playlists), and then go back to the playing tab, tap shuffle, then tap next.

**Describe the solution you'd like**
I think that adding a new option along similar to the following will be a great way to add this feature:
```
showShuffleButtonOnPlaylists: true # default is false, shows a button on favorite and Spotify playlists to start playing in shuffle mode
```

It would make it where it starts playing a random song from the playlist and ensures that its setup to play on shuffle (we want to make sure the initial song is different each time too).

Example concept image:
![IMG_BC49AAEE6B3F-1](https://github.com/johanfrick/custom-sonos-card/assets/518673/a60e14a8-6711-451a-962c-c7e7971b4a18)

**Describe alternatives you've considered**
- I considered the ability to state specifically which playlists should include the shuffle button, but I don't think thats the right way since as people add playlists they'll probably want the button there. Along with the Spotify app itself has a shuffle paly button included for each playlist now.

**Additional context**
As Sonos doesn't "technically" or "properly" support access point style wifi setups, this Sonos Card is the main way I control music in my house. So features like this make it closer to an all-in-one controller.

**Comment by johanfrick** [comment]
Not sure this can implemented in a decent way. Shuffle mode is not something you can pass along while telling home assistant to play something on Sonos. Shuffle mode is a separate call. On top of that, some media does not support shuffle, so if you for instance are playing a radio station and then want to play a playlist, it is not possible to set shuffle mode before starting the playlist. If you try that sonos will ignore the shuffle mode. This means that you have to first tell home assistant to play the playlist, then tell home assistant to enable shuffle mode, then tell home assistant to play next song.
