### ISSUE TITLE
Hide items in Media Browser

### ISSUE THREAD

**Issue by sanderlv** [johanfrick/custom-sonos-card#183]
**Is your feature request related to a problem? Please describe.**
I would like to disable some lines in the card. E.g,:
![image](https://github.com/johanfrick/custom-sonos-card/assets/16528916/ad0752a7-aab5-40df-9226-02f3a2471b1d)

Synology Photos 

**Describe the solution you'd like**
Being able to toggle lines in the favorites section of the card

**Describe alternatives you've considered**
Trying to search for open issues/questions. Trying the HA forum

**Additional context**
i think it is pretty claer now :-)

**Comment by johanfrick** [comment]
Did you look in the readme? 😉
’mediaBrowserTitlesToIgnore’

**Comment by sanderlv** [comment]
Yes I did, and now still I do not really "get" this is what I need :-).

Thanks, I'll have a look!

**Comment by sanderlv** [comment]
That was easy. Now I have a 2nd question I cannot find after reading. Hope I am not missing this as well :-(.

I now have:
![image](https://github.com/johanfrick/custom-sonos-card/assets/16528916/eafcda7f-a4d0-4594-a8af-3f6d727d2430)

How can I circumvent to press the icon in the top right before it shows me the favorites?
![image](https://github.com/johanfrick/custom-sonos-card/assets/16528916/1a3bab76-27c1-43d8-8ae2-aad14a391e30)

**Comment by johanfrick** [comment]
The state of that is saved in the app/browser. So you only need to press it once (on every device)

**Comment by johanfrick** [comment]
Thanks!

---

[BMC ☕️](https://www.buymeacoffee.com/punxaphil)
