### ISSUE TITLE
No play all option with local server

### ISSUE THREAD

**Issue by AlbertShovelton** [johanfrick/custom-sonos-card#185]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**

V6.10.1

**Last working release (if known):**

**Browser and Operating System:**

HAOS 11.1 Home assistant 2023.10.1. iPhone app.

**Description of problem:**

Set up a local media server through the sonos app. It appears in the Sonia card, however the play button does not work forcing me to play each song individually. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by johanfrick** [comment]
Thanks for reporting. Will see if I can reproduce this.
