### ISSUE TITLE
Favourite Thumbnails

### ISSUE THREAD

**Issue by billyburks** [johanfrick/custom-sonos-card#19]
**Checklist:**

- [ Y] I updated to the latest version available
- [ Y] I cleared the cache of my browser

**Release with the issue:** 2.3.2

**Last working release (if known):** N/A

**Browser and Operating System:** Chrome Version 98.0.4758.109 (Official Build) (x86_64)
MAC OSX Big Sur 11.6.4

**Description of problem:**Not all Favourite Thumbnails are showing, see screenshots of Custom-Card and my SONOS Favourites
<img width="1440" alt="Screenshot 2022-02-23 at 16 32 17" src="https://user-images.githubusercontent.com/34285592/155363783-46e467ea-5d16-4712-b72f-8813ab393652.png">
<img width="1332" alt="Screenshot 2022-02-23 at 16 32 08" src="https://user-images.githubusercontent.com/34285592/155363797-47c07e26-07fd-43a1-adb3-d1268c5458ac.png">

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by johanfrick** [comment]
Fixed by [Bugfix: Missing some types of favorites](https://github.com/johanfrick/custom-sonos-card/commit/cf42fbdd4cad9953103d7303ef5ac38b5d177bbe)[](https://github.com/johanfrick)
