### ISSUE TITLE
Progress bar not showing

### ISSUE THREAD

**Issue by Emilef22** [johanfrick/custom-sonos-card#192]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
IDK if the problem is maybe linked, but the progress bar is invisible in the custom mini media player card, but it is ok on the meda player card of HA

**Comment by Emilef22** [comment]
Since the 2023.11 update, the progress bar disappeared from the card.

**Comment by johanfrick** [comment]
> custom mini media player card
This repo is about the Sonos Card, did mean to report this in https://github.com/kalkih/mini-media-player ?

**Comment by Emilef22** [comment]
I think that sonos card dont depends of mini media player, but the problem may come from the same source. I did report it on mini media player too.

**Comment by johanfrick** [comment]
Can you provide a screenshot?

**Comment by Emilef22** [comment]
<img width="1512" alt="Capture d’écran, le 2023-11-08 à 18 58 14" src="https://github.com/johanfrick/custom-sonos-card/assets/97327371/37c08ffa-0cad-42b1-971e-4081864875be">

**Comment by johanfrick** [comment]
Thanks! I'll look into this

**Comment by johanfrick** [comment]
Please verify @Emilef22

**Comment by Emilef22** [comment]
Still nothing, I cleared my cache, di i have to reinstall the card?

**Comment by Emilef22** [comment]
Thank you!!! Works perfectly :)
