### ISSUE TITLE
Add functionality to change source.

### ISSUE THREAD

**Issue by sh00t2kill** [johanfrick/custom-sonos-card#193]
**Is your feature request related to a problem? Please describe.**
The default HA media player card allows a user to change the source of a sonos device where applicable (eg a sound bar)

**Describe the solution you'd like**
It would be great if this card could do that

**Comment by johanfrick** [comment]
Good suggestion, I'll take a look

**Comment by dwheaton-paloit** [comment]
If you dont hae any devices that can switch source, im happy to help out as i have a couple of mine setup in my test HA instance.

**Comment by sh00t2kill** [comment]
If you dont have any devices that can switch source, im happy to help out with testing as i have a couple of mine setup in my test HA instance.
