### ISSUE TITLE
Ability for playlist to continue when a single track is selected and other observations

### ISSUE THREAD

**Issue by gtothill** [johanfrick/custom-sonos-card#195]
**Is your feature request related to a problem? Please describe.**
Firstly - this is superb - it has changed the way we use HA in our house. Thank you. I have some observations and suggestions. Forgive me if I group them. Happy to split them out if necessary and if they are worth pursuing.

1) If an individual track is selected in a playlist it is played and then playback stops. This is not the user experience in other systems where the intent is simply to move back and forth through a playlist and not treat the selection of a track as an individual, discreet playback event. It would be nice if the playback of the playlist continued after this event.

2 ) It would be good if the ‘recently played’ list had the ability to play it like a playlist, rather than just individual tracks, similarly the ‘Top Tracks’ section.

**Describe the solution you'd like**

1) Playlists resume after an individual track in that playlist is selected. Ie tracks are treated as a continual playlist and simply carry on to the next if selected.

2) Recently played and Top Tracks lists can be treated as playlists.

**Describe alternatives you've considered**

Not managed to work out an alternative solution except moving all the recently played and top tracks to their own playlists in Spotify.

**Additional context**

None, but thanks for considering!

**Comment by johanfrick** [comment]
I've been thinking about this too, but I am not sure it's possible. Can you make it work like that in the built in media browser?
http://homeassistant.local/media-browser

**Comment by johanfrick** [comment]
This card now uses Home Assistant's built in media browser, relying on whatever features are there for browsing media.
