### ISSUE TITLE
[FR] Browse media

### ISSUE THREAD

**Issue by giuliandenicola1** [johanfrick/custom-sonos-card#20]
Wow alot has happend when since I created my pull request, looks awesome!

At the time I tried to add the browse media button because I would give me alot of room to choose from spotify, etc. instead of only my preset sources. I'm not a programmer so unfortunately I couldn't figure out how.

Can you add the browse media button? Or make it optional. Maybe an idea to put it in the 3rd column?
<img width="447" alt="Schermafbeelding 2022-02-25 om 09 43 01" src="https://user-images.githubusercontent.com/67443916/155684476-0f242057-679b-4b6f-86a0-e2a5731bbb99.png">

Cheers.

**Comment by johanfrick** [comment]
I don’t think that is supported by home assistant. Have you seen that functionality in any other card? To browse Spotify?

**Comment by giuliandenicola1** [comment]
Yes, it's the media browser from home assistant itself 😄 Just add the official spotify integration to home assistant and it will appear in the browser.

**Comment by giuliandenicola1** [comment]
https://user-images.githubusercontent.com/67443916/155745721-3d8cd65c-5edb-4976-a322-75b0152be7c5.mov

**Comment by johanfrick** [comment]
Here is rough beta https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.0.0-beta
Probably needs some more TLC, but please give it a try and see how it works for you.
@giuliandenicola1 @cstrand89

**Comment by mfabiani53** [comment]
Yes, i agree, very good idea and maybe a button little bigger would be perfect...

**Comment by johanfrick** [comment]
Any suggestions how?

**Comment by mfabiani53** [comment]
First of all the Spotify logo... :-)

**Comment by johanfrick** [comment]
New beta available, how do you like it? [v3.0.0-beta2](https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.0.0-beta2)
@mfabiani53 @giuliandenicola1 @cstrand89

**Comment by cstrand89** [comment]
How do I actually activate it so I can see the media box? @johanfrick

**Comment by giuliandenicola1** [comment]
> How do I actually activate it so I can see the media box? @johanfrick

In HACS:
<img width="636" alt="Schermafbeelding 2022-03-05 om 09 50 51" src="https://user-images.githubusercontent.com/67443916/156876078-6947dc1b-d2ac-44b2-bc41-22de377ee91d.png">

Or sideload: https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.0.0-beta2

**Comment by cstrand89** [comment]
Ah perfect! I had activated beta but for some reason it hadn't been downloaded yet.

**Comment by johanfrick** [comment]
@cstrand89 @mfabiani53 @giuliandenicola1 Please try this new beta:
https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.0.0-beta3

**Comment by johanfrick** [comment]
https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.0.0-beta5

**Comment by giuliandenicola1** [comment]
Nice, but what are the new layout settings because on beta 5 I’m getting a config error.

**Comment by cgeroldinger** [comment]
Same here on beta 5
![image](https://user-images.githubusercontent.com/40886256/156986521-68f440b5-9bf3-4d0d-8d54-6e6860e73c62.png)

**Comment by giuliandenicola1** [comment]
![PNG-afbeelding](https://user-images.githubusercontent.com/67443916/156988581-192dde87-c696-47ff-beee-565d81107bce.png)

**Comment by johanfrick** [comment]
Thanks for testing it! New beta with a fix: https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.0.0-beta6

**Comment by cgeroldinger** [comment]
I can confirm that beta6 works for me.  All back

**Comment by johanfrick** [comment]
Looks like we are close to releasing this. Any other glitches related to "browse media" that should be addressed before releasing?

**Comment by giuliandenicola1** [comment]
I’m not experiencing any issues.

**Comment by giuliandenicola1** [comment]
> Any other glitches related to "browse media" that should be addressed before releasing?

I did find an issue right now and it's related to the text to speech folder in the browse media section.

When going to tts in the official browse media of home assistant you are presented with a text field where you can type in text and have it speak on all the connected speakers.

When going to tts in the browse media of the custom sonos card it's empty. 

You could remove it because it has nothing to do with music, but on the other hand it's no harm to have it.

Greetings.

**Comment by johanfrick** [comment]
Thanks @giuliandenicola1 , v3.2.1 released to fix it. Please test it

**Comment by giuliandenicola1** [comment]
Working fine!

**Comment by giuliandenicola1** [comment]
Can you also add the camera folder to the filter? It's incompatible with sonos speakers anyways!

**Comment by johanfrick** [comment]
I don't have cameras myself, so not sure what to filter out. Can you debug it for me?
Go to media browser, then open devtools, then network, then websockets. I am looking for the media_content_id. Here is an example for tts:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/26582898/157559446-267ac801-2ba4-479c-8cd9-cc98f3d373c5.png">

**Comment by giuliandenicola1** [comment]
Got it:
```
children: [{title: "Camera", media_class: "app", media_content_type: "app",…},…]
  0: {title: "Camera", media_class: "app", media_content_type: "app",…}
    media_content_id: "media-source://camera"
```

**Comment by johanfrick** [comment]
Great! Fixed here: https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.5.1
