### ISSUE TITLE
Possibility to make the card smaller?

### ISSUE THREAD

**Issue by mrKayne** [johanfrick/custom-sonos-card#210]
So I like the features in general, but the player card is just rather big.

Would it be possible to make it the same size as the standard sonos card?
Instead of having a square image of the cover, it can be the background of the card itself, just as the standard sonos card.

Then make the audio-control buttons smaller, move them to the left, make the volume-slider smaller and move it up next to the buttons on the right. Keep the buttons for playlists/grouping/etc on a line of it self.

That would be awesome!

**Comment by johanfrick** [comment]
Sounds like a big redesign. I'm not totally against it, but I would need some mockups to make sure it works with the features of the card. I'll close this issue, but feel free to reopen once you have mockups to show.

**Comment by m-idler** [comment]
Maybe this is an idea or helps somebody - i just rearranged the grid a little bit using `card_mod`. Maybe this is an option for different layout that are configurable like for mushroom cards...

![Screenshot 2023-12-29 at 00 16 29](https://github.com/johanfrick/custom-sonos-card/assets/2026873/1f1bc95c-eb8b-488b-9037-aab36a4b42ec)

With this config:
```
type: custom:sonos-card
          card_mod:
            style:
              sonos-player $: |
                .container {
                  grid-template-rows: min-content min-content !important;
                  grid-template-areas:
                    'header header'
                    'artwork controls'  !important;
                  grid-template-columns: 25% auto !important;
                  min-height: auto !important;
                }        
          sections:
            - player
            - media browser
            - grouping
            - volumes
          topFavorites:
            - ''
          hideGroupCurrentTrack: false
          dynamicVolumeSlider: true
          hideBrowseMediaButton: false
          showVolumeUpAndDownButtons: true
          excludeItemsInEntitiesList: false
          mediaBrowserItemsPerRow: 5
          entities: []
          entityId: media_player.sonos_move
          heightPercentage: 50
```

**Comment by johanfrick** [comment]
Yeah, maybe. Doesn't look too great to me, but it is a matter of taste I suppose.
It is quite similar to this card mod example: https://github.com/johanfrick/custom-sonos-card/discussions/229#discussioncomment-7780864

Maybe it is enough to just use card_mod for this. Otherwise, feel free to create a PR.
