### ISSUE TITLE
Home Assistant app on iOS freezes when browsing for german radio 

### ISSUE THREAD

**Issue by robinnibor94** [johanfrick/custom-sonos-card#211]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** latest - v6.11.2

**Last working release (if known):** n/a

**Browser and Operating System:** Safari - iPad-OS 16.6 & Safari - iOS 17.1.1

**Description of problem:** While trying to browse for german radio (via Radio Browser app), the Home Assistant app starts to freeze. I tried to browse for albanian radio just to check if this is happening with every „folder“. Albanian radio is working fine. My feeling is that there are to many radio channels available in Germany and the Sonos card front-end is starting to freeze for this reason. This is happening on iOS + ipad-OS.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by johanfrick** [comment]
Thanks for reporting, I'll look into pagination.

**Comment by robinnibor94** [comment]
Thanks for looking into it that fast! Using the HA built-in browsing function is working fine - thank you very much. I pretty much liked the customized sonos card browsing fuction as the built-in browsing window was scaling to the size of the tile-card automatically. Do you think this is somehow possible again? If not - i will anyway use to custom sonos card as it looks pretty nice :-)

One additional question:

1. Is it possible to close the overlay after a song has been chosen? Jumping back to the "dashboard" to the home menu (see picture) would be nice. As this might be anoying for some of the users, maybe this could be a setting that can be disabled/enabled? :)

Have a nice day
Robin

![custom sonos card](https://github.com/johanfrick/custom-sonos-card/assets/150392360/8c797e6e-4db9-45c6-a2aa-043fb2a5aacf)

**Comment by johanfrick** [comment]
I am aware there are some drawbacks with this solution, but the big benefit is stability. And I think it is worth it. 

As far as I see there is no way to customise the built in media browser dialog. So I believe we have to live without auto-closing dialog, without automatically switching to home view, and no way to embed browsing within the card, until Home Assistant expose more functionality (or someone tells me there is a way that I wasn't able to find in my research).

**Comment by johanfrick** [comment]
Main topic of this is is fixed with https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.13.0. Closing.

**Comment by johanfrick** [comment]
Feel free to create a new issue for the other part.
