### ISSUE TITLE
Audio files in "my media" not displaying

### ISSUE THREAD

**Issue by Ay1tsMe** [johanfrick/custom-sonos-card#220]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v6.11.3
**Last working release (if known):**

**Browser and Operating System:**
Every browser and phone

**Description of problem:**
Not sure if this is a bug or I haven’t configured correctly but when I browse local media through the custom sonos card, it does not display any of my audio files to play. I can see the media and play it in the default media dashboard in home assistant but not in the sonos card. Any suggestions?
Sonos Card:
![image](https://github.com/johanfrick/custom-sonos-card/assets/110982014/6e7363e6-49b2-4ac2-b3e7-b0a65430ad3e)
Media Browser:
![image](https://github.com/johanfrick/custom-sonos-card/assets/110982014/fff358b7-cd57-4837-b23e-a874dbe0f451)

**Comment by johanfrick** [comment]
A new beta is released which uses Home Assistant's built-in browser. Please try it out and let me know if you find any issues:
https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.12.0

<img width="507" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/26582898/a8f4706f-c1bd-4743-901c-b6698997f563">


---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by Ay1tsMe** [comment]
Okay I can see and select my local media now which is great. Although I can't choose the play the whole folder or queue up music. I can only play one individual song. I believe this is a limitation of the media integration and not with your software.

Also, when I play local media, it just says no media selected as the title. But it gets the album cover and name of the album correctly. I'm almost positive the metadata for the file is correct because they are songs I've added to my iPod and they are shown correctly there.

**Comment by johanfrick** [comment]
I'll try to dig into that, can you give me some more info?
If you go into developer tools (http://homeassistant.local/developer-tools/state and take a screenshot of your player that shows "No media selected", and share that screenshot here

**Comment by Ay1tsMe** [comment]
Okay it shows the artist in the title but not the song name. Here Is an example:
![Screenshot_2023-12-04-08-17-48-67_c3a231c25ed346e59462e84656a70e50](https://github.com/johanfrick/custom-sonos-card/assets/110982014/f9caf369-1f9d-49dc-867e-737dcebb607e)

My developer tool attributes are here for the sonos media player:
![Screenshot_2023-12-04-08-20-52-26_c3a231c25ed346e59462e84656a70e50](https://github.com/johanfrick/custom-sonos-card/assets/110982014/fcfdeef0-ab57-40f6-bb2c-4f29b9b673ca)

From what I can see there is no media title attribute when playing local media. Which is strange considering there is an attribute created when playing Spotify. Home assistants solution to this problem in there integrated media player is to display the filename instead of the metadata. Which isn't as pretty but at least you know the song name.

**Comment by johanfrick** [comment]
The main topic of this issue is fixed, so I will close it. Fix is in https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.13.0

I'm afraid I can't directly see how to get the filename. If you find out how get the filename, please create a PR or create an issue with the suggested solution.
