### ISSUE TITLE
Scrubbing through song

### ISSUE THREAD

**Issue by Ay1tsMe** [johanfrick/custom-sonos-card#221]
Is there a way to scrub through audio? On the default media player for home assistant, I’m able to select a position in the song. Is this also possible through the Sonos card? I haven't seen many people talk about it but it's annoying having to go to the home assistant default media player and scrub to a position in the song instead of being able to do it in the sonos card.

**Comment by johanfrick** [comment]
@Ay1tsMe Please try this out in https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.13.0
