### ISSUE TITLE
Oh no what happened after 6.13.0

### ISSUE THREAD

**Issue by sanderlv** [johanfrick/custom-sonos-card#228]
Before the "list" was in the card... Now it is not anymore:
![image](https://github.com/johanfrick/custom-sonos-card/assets/16528916/0c76e362-b435-4c80-9ac4-941cde55f9e9)

Browse media opens another dialog

**Comment by johanfrick** [comment]
I'm not sure I understand what is the problem. Can you elaborate?

**Comment by sanderlv** [comment]
Yes, before update the "media list" was in the above screenshot, in the card. Now it is not anymore. Remember I asked to not press the arrow everytime and you implemented that. Now there is no arrow but a "browse media" button. And that opens an external selector:

![image](https://github.com/johanfrick/custom-sonos-card/assets/16528916/35280865-0266-486a-ae15-84d1a91029fd)

**Comment by sanderlv** [comment]
See screenshot here how it was: https://github.com/johanfrick/custom-sonos-card/issues/183

**Comment by johanfrick** [comment]
Yes, now you need to use that. Or add to your Sonos favourites.

**Comment by johanfrick** [comment]
It has become an increasingly hard task to try and maintain a self-written media-browser and try to match what Home Assistant's built-in media browser can do. This area has been the one with the most bugs and issues reported. Because of this the decision is to only show favorites in media section, and for other media the user can use HA's built-in media browser dialog.

**Comment by sanderlv** [comment]
Understand.

I was so happy with it... 

Any idea how to "Filter" out the unwanted icons there?

**Comment by phateks** [comment]
After Update , card vanished
![image](https://github.com/johanfrick/custom-sonos-card/assets/134103405/25fd74f2-fc29-4f2f-9a2f-68462125fa00)

**Comment by johanfrick** [comment]
Must be some browser cache issue or similar, I hear it's working for others.

**Comment by johanfrick** [comment]
> Understand.
> 
> I was so happy with it...
> 
> Any idea how to "Filter" out the unwanted icons there?

I'm afraid not, that should be a request to the team building the [frontend](https://github.com/home-assistant/frontend)

**Comment by phateks** [comment]
cleared cache several times, used 2 pc-s to test, and phone, just gone. i can't figure out what happened.

**Comment by phateks** [comment]
uninstalled card, uninstalled lovelace (cuz i had a similar problem few month ago, and hed to reinstall everything on RPI), installed older version , and lovelace, rebooted, still the same :((

**Comment by adamlynes** [comment]
Nope, it stays the same, even after a hard refresh

**Comment by johanfrick** [comment]
And the old version of the card is working for you?

**Comment by adamlynes** [comment]
Yes, just removed via HACS and then downloaded 6.11.3 and it works fine.

**Comment by phateks** [comment]
so, maybe there is something else and i don't see it.
just uninstalled from hacs ,rebooted, an still seeing something like this
![image](https://github.com/johanfrick/custom-sonos-card/assets/134103405/d82455ec-cf53-4d18-bdb2-69197403b822)

what am i missing?

**Comment by johanfrick** [comment]
How about 6.12.1?

**Comment by adamlynes** [comment]
I don't see an option to download any of the .12 versions

**Comment by adamlynes** [comment]
Cheers!

**Comment by phateks** [comment]
just restored a backup from nov 30, and immediately after i updated music assistant the card vanished.
this info is of any use for you?

**Comment by adamlynes** [comment]
Installed and working for me - thanks @johanfrick!
