### ISSUE TITLE
Possibility to write the selected speaker to a variable to be used in a call service button card.

### ISSUE THREAD

**Issue by misterwesley** [johanfrick/custom-sonos-card#231]
I have certain playlist that I call with a button card on the speaker that I have selected in a selection list. (See my select speaker card)
Is it possible to write the value of the selected speaker in the groups card to an input select or other variable so that I can press the custom spotify or radio button to play that music on the selected speaker?

These playlists don't show up in the favorites so I can't create a browser card with those playlist as a favorite.

Example of a spotify button:
`        tap_action:
          action: call-service
          service: media_player.play_media
          service_data:
            media_content_id: >-
              spotify://29333ea597842e688a1113a34f0cf392/spotify:playlist:1s5Ln6ZfcKMFSJxdLXKFIY
            media_content_type: spotify://playlist
            entity_id: '[[[ return states["input_select.welke_speaker"].state ]]]'`

![afbeelding](https://github.com/johanfrick/custom-sonos-card/assets/121464535/5c67efce-86eb-46b1-9d4c-4fc9267b8ad2)

**Comment by johanfrick** [comment]
Why don't you add the playlist to favourites? That would make it a lot easier.

**Comment by misterwesley** [comment]
That is also possible but I can't find the place to add a playlist to my favorites anywhere. Also not all my Spotify playlists show up in the media browser.

**Comment by misterwesley** [comment]
The video doesn't seem to be loading. Can you share it again?

**Comment by johanfrick** [comment]
That's why it's called Sonos card

**Comment by johanfrick** [comment]
Sure, you'll need [card_mod](https://github.com/thomasloven/lovelace-card-mod):
```yaml
type: custom:sonos-card
card_mod:
  style:
    sonos-media-browser$: |
      sonos-media-browser-header {
        display: none;
      }
```
