### ISSUE TITLE
Card info does not fit within set card size

### ISSUE THREAD

**Issue by adamzeis** [johanfrick/custom-sonos-card#232]
Version 6.13.4, I'm seeing the info on my card not fit as it used to. Not sure if there's an issue with my code or if something broke along the way. Seemed to be fine in previous releases. This is happening in Safari, Chrome and through the HASS iOS app. 

I've tried multiple browsers, updated and restarted HASS with no luck. It could very well be something in my setup as I'm still a HASS newbie. 

![Screen Shot 2023-12-08 at 12 19 07 PM](https://github.com/johanfrick/custom-sonos-card/assets/39461983/9b81029b-ca7e-4d87-adad-4967a3b6b4fd)

**Comment by johanfrick** [comment]
Thanks for reporting! A bug sneaked in there when switching to CSS Grid.
