### ISSUE TITLE
FR - add classes to other buttons to make styling easier like the .big-icon class

### ISSUE THREAD

**Issue by schmierlappe** [johanfrick/custom-sonos-card#233]
**Describe the solution you'd like**
Maybe it is possible to add some more classes to the other buttons to have more options to style them as it already exist for the big play/stop button.

![image](https://github.com/johanfrick/custom-sonos-card/assets/4019953/340de64d-ae2c-4d6b-9114-81c52dbf96c9)

or maybe there is another better way to do that. Theming variables or so.

Thx

**Comment by johanfrick** [comment]
Please describe your use case

**Comment by schmierlappe** [comment]
I want to style them. Give them another Background Color and change color of icon

**Comment by johanfrick** [comment]
Have you tried theming? https://github.com/johanfrick/custom-sonos-card#theme-variables

**Comment by schmierlappe** [comment]
yeah sure I have set this in my theme which works fine but not for the media controls buttons

      accent-color: var(--red)
      primary-color: var(--contrast20)
      secondary-text-color: var(--contrast17)
      secondary-background-color: var(--contrast)

![image](https://github.com/johanfrick/custom-sonos-card/assets/4019953/49db9c09-584f-4f12-bf8c-7f0e3f792413)

this my card with card mod

`
    card_mod:
      style:
        sonos-player$:                                                    
          .: |
            div.artwork {            
              background-size: cover;
              border-radius: 12px;
              width: 75%;
              height: 100%;
              display: flex;
              justify-self: center;
            }  
          sonos-player-controls$:
            .: |
              .big-icon {
                background: var(--red);
                border-radius: 50%;
                margin: 5px;             
              :host {
                background: var(--red) !important;
                border-radius: 50%;
              }                   
        .: |
          ha-card:before {
            background: url( '{{ state_attr("media_player.sonos_media_player", "entity_picture") }}') center no-repeat;   
            transform: translate3d(0,0,0);
            -webkit-transform: translate3d(0,0,0);
            content: "";
            position: absolute;
            height: 100%;
            width: 100%;
            background-size: 40% 40%;
            filter: blur(150px) saturate(200%); 
          }
          ha-card {
            transform: translate3d(0,0,0);
            -webkit-transform: translate3d(0,0,0);     
          }
`

**Comment by johanfrick** [comment]
Ah, now I understand.
Try something like this:
```yaml
type: custom:sonos-card
card_mod:
  style:
    sonos-player$ sonos-player-controls$: |
      .icons * {    
        --mdc-icon-button-size: 1.5rem !important;
        --mdc-icon-size: 1.5rem !important;
        color: pink;
      }
```
