### ISSUE TITLE
Versions after 2.2 stop recognizing 2 of my 4 sonos units

### ISSUE THREAD

**Issue by paulearley** [johanfrick/custom-sonos-card#24]
I have been updating the sonos card for several weeks and am enjoying the updates.  However, since Tuesday - 2/22 the card has dropped 2 of my 4 sonos players. This is most likely related to the fact that I have my players on a different subnet from the Ubuntu computer running home assistant; there are firewall rules that control communication between the subnets. 

The previous card versions worked. I tried adding back the "entities" section listing my sonos entities in beta-15 and this did not fix the problem. This may be asking a lot, but is it possible to have the option of specifying entities (to go around auto-detect)?

**Comment by paulearley** [comment]
Hold off on this... I may have found a workaround for this problem.

**Comment by johanfrick** [comment]
Ok, great. Please share solution, it might help others :-)
Also, if the problem comes back, it would be awesome if you could find out which release version that it stopped working to make the problem easier to investigate.
Closing the issue, but feel free to reopen if it becomes a problem again.
