### ISSUE TITLE
Optionally hide "Browse Media" button

### ISSUE THREAD

**Issue by bdsoha** [johanfrick/custom-sonos-card#240]
**Is your feature request related to a problem? Please describe.**

The `"Browse Media"` button displays many entities *(i.e. cameras, music, sonos, etc.)*.
In many cases, a list of favorites is all that is desired.
Previous versions of this card allowed unwanted sources to be hidden using the `mediaBrowserTitlesToIgnore` configuration array.
Since the media browser was replaced with the native browser, the abovementioned configuration was lost.

**Describe the solution you'd like**
Add a `boolean` configuration to hide the `"Browse Media"` button when displaying the *media browser section*.
As a result, only `"All Favorites"` will be displayed.

**Comment by johanfrick** [comment]
Please try it in this beta: https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.14.0
Let me know if it works as expected, then I will release it

**Comment by bdsoha** [comment]
Thanks for the quick release.
The option works, but the top padding is off.

### Before

![image](https://github.com/johanfrick/custom-sonos-card/assets/4192777/317473d0-a981-476b-9a80-ea67bd175d38)

### After

![image](https://github.com/johanfrick/custom-sonos-card/assets/4192777/098b9644-9e8d-45b7-9cc0-546f217ee00a)

**Comment by johanfrick** [comment]
better? 
[v6.13.8-beta-debug-3](https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.13.8-beta-debug-3)

**Comment by bdsoha** [comment]
Couldn't be better!

**Comment by johanfrick** [comment]
released: https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.14.1
