### ISSUE TITLE
Card not showing using iobroker

### ISSUE THREAD

**Issue by boe322** [johanfrick/custom-sonos-card#241]
Checklist:

    [x ] I updated to the latest version available
    [x ] I cleared the cache of my browser

Release with the issue:
v6.13.7

Last working release (if known):
-

System Setup:
RasPi 4B running:
IoBroker v6.10.1
js-controler 5.0.12
lovelace adapter v 3.0.1
sonos adapter v 3.0.0

working custom cards: 
- button-card
- simple thermostat

Automatic detection of entities didn't work, manual entry of entities won't work either.
Card doesn't show
Card "media-control" working (limited) with Sonos entities

![Screenshot from 2023-12-18 10-08-49](https://github.com/johanfrick/custom-sonos-card/assets/154215297/b169c339-1d62-4499-9c5a-13220355b6fc)

**Comment by johanfrick** [comment]
Thanks for reporting, I'll look into this

**Comment by johanfrick** [comment]
I only support Home Assistant, never heard of iobroker. Feel free to come with a PR though.
