### ISSUE TITLE
Card was there in a dashbaord, then disappeared

### ISSUE THREAD

**Issue by atclaus** [johanfrick/custom-sonos-card#249]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v6.14.3

**Last working release (if known):**
n/a

**Browser and Operating System:**
Firefox on PC, iOS HASS app
HASS running on Raspberry Pi 4 with HASS in a docker container
Core 2023.12.3
Frontend 20231208.2

**Description of problem:**
- _might be my own mess up of install. apologies if so. but it worked then stopped_
- Get via HACS
- Was prompted at download that and downloaded

> ```
> When downloaded this will be located in '/config/www/community/custom-sonos-card'
> 
> After the download completes, since you are not using Lovelace in storage mode you need to manually add the resource with these settings:
>                 url: /hacsfiles/custom-sonos-card/custom-sonos-card.js
>                 type: module
> ```

- found at `www/community/custom-sonos-card/custom-sonos-card.js`
- modified `configuration.yaml` to the below (some form the of the second URL worked, then without _recalling_ a change, stopped when I next opened the app? Tried various versions of the url, going to `../www/commu...` and so on, to no avail.

> 
> ```
> lovelace:
>   mode: yaml
>   resources:
>     - url: /webrtc/webrtc-camera.js
>       type: module
>     - url: /www/community/custom-sonos-card/custom-sonos-card.js
>       type: module
> ```

- showed and worked in browser, phone, iPad.
- next time went to use, failed to be found. Do not _recall_ any changes to HASS in between (was just a few hours)
- get that "custom element does not exist", and no longer in UI editor as option, unlike the webrtc-camera

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by johanfrick** [comment]
I can't see that this error is because of the Sonos card. Sounds like a more generic issue with your setup. You could try with other custom cards from HACS, I'm quite sure if you get them to work this will also work.
