### ISSUE TITLE
Error structuredClone is not defined in FullyKioskBrowser

### ISSUE THREAD

**Issue by polemikrat** [johanfrick/custom-sonos-card#258]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
V.6.14.4

**Last working release (if known):**

**Browser and Operating System:**
FullyKioskBrowser on KindleFire

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:
Some Browsers do not support structuredClone. I think a lot of people are using FullyKioskBrowser for Tablet Dashboards.

**Comment by johanfrick** [comment]
Thanks for reporting!
Fixed https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.14.5
