### ISSUE TITLE
Show "Audio Input Format" on Sonos Card

### ISSUE THREAD

**Issue by domalab** [johanfrick/custom-sonos-card#259]
Thanks for the amazing work on the Sonos card. It's very handy.

**Is your feature request related to a problem? Please describe.**
No, its not an issues.

**Describe the solution you'd like**
It will be a nice to be able to view the audio input format when playing media. Eg. When a movie is played the Sonos card can show if its audio input format is Dolby Atmos, PCM 2.0, etc.

The Sonos integration shows "Audio Input Format" under diagnostics:
 
![Screenshot 2023-12-31 at 10 55 41 am](https://github.com/johanfrick/custom-sonos-card/assets/57021511/096d574a-4042-4db0-9a4d-48386997ad2e)

When media is played it shows this via Sonos integration:

![Screenshot 2023-12-31 at 10 55 23 am](https://github.com/johanfrick/custom-sonos-card/assets/57021511/770db5a6-8476-40cf-8d91-76b0c546658c)

It looks like this in the Sonos App. Maybe it can be located above the volume slider on your Sonos Card?

![Screenshot 2023-12-31 at 11 00 21 am](https://github.com/johanfrick/custom-sonos-card/assets/57021511/ca67ebc7-1f12-45aa-a2d4-42ca628279e1)

**Describe alternatives you've considered**
None

**Additional context**

**Comment by johanfrick** [comment]
Good suggestion! I'll take a look

**Comment by johanfrick** [comment]
How is this:
[v6.15.0-beta2-audio-input-format](https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.15.0-beta2-audio-input-format)
<img width="481" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/26582898/2c78dfbb-4c0a-4aa8-8ca6-852a4576ae31">

<img width="487" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/26582898/d8a033fd-9445-457b-b445-dcea9c8e825f">

**Comment by domalab** [comment]
That looks great!! 👍🏻

On 3 Jan 2024, at 7:00 am, Johan Frick ***@***.***> wrote:

﻿

How is this:
v6.15.0-beta2-audio-input-format<https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.15.0-beta2-audio-input-format>
image.png (view on web)<https://github.com/johanfrick/custom-sonos-card/assets/26582898/2c78dfbb-4c0a-4aa8-8ca6-852a4576ae31>

image.png (view on web)<https://github.com/johanfrick/custom-sonos-card/assets/26582898/d8a033fd-9445-457b-b445-dcea9c8e825f>

**Comment by johanfrick** [comment]
released
https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.15.0
Use `showAudioInputFormat: true` to show it in the player section
