### ISSUE TITLE
Texts bigger?

### ISSUE THREAD

**Issue by mfabiani53** [johanfrick/custom-sonos-card#29]
Is there a way to make texts in all sections bigger than now?

Actually some sections are really difficult to read as the examples above:

![Schermata 2022-03-01 alle 12 43 59](https://user-images.githubusercontent.com/37701688/156163522-388e2252-97f3-408c-a6a6-b90b0612e965.png)

![Schermata 2022-03-01 alle 12 44 40](https://user-images.githubusercontent.com/37701688/156163399-5277ae2e-4e15-49ab-b451-fc818c1ae195.png)

**Comment by giuliandenicola1** [comment]
#34

**Comment by johanfrick** [comment]
Should be handled here: https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.0.0
