### ISSUE TITLE
Sonos Card displaying drop as a full list

### ISSUE THREAD

**Issue by cloudbr34k84** [johanfrick/custom-sonos-card#30]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
HA core-2022.3.0

**Last working release (if known):**
HA core-2022.2.9
**Browser and Operating System:**
GC Version 98.0.4758.102 (Official Build) (64-bit)
Home Assistant OS 7.4
Zorin OS 16

**Description of problem:**
The attached screenshot pretty shows the issue, but the card when you go to edit is also just showing the full drop down list

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
![image](https://user-images.githubusercontent.com/58960644/156483692-0c42434f-040d-4dd0-b8c1-c423ffbf6cba.png)
![image](https://user-images.githubusercontent.com/58960644/156485014-56ccd825-bd74-489a-8bd8-f63ae5515d73.png)

**Comment by giuliandenicola1** [comment]
You're probably in the wrong repository.
https://github.com/kalkih/mini-media-player

**Comment by cloudbr34k84** [comment]
Ahh crap thank you!
