### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by cstrand89** [johanfrick/custom-sonos-card#37]
The graphics are now showing with rounded corners (even the main picture) on my end after the latest update
<img width="1155" alt="Screenshot 2022-03-09 at 14 03 18" src="https://user-images.githubusercontent.com/42031176/157457407-1e3331d7-20a3-49c4-866d-669445ecf3c5.png">
.

**Comment by johanfrick** [comment]
Any idea, @giuliandenicola1 ?

**Comment by cgeroldinger** [comment]
Strange. I also updated and stil see all good + mute b utton
![image](https://user-images.githubusercontent.com/40886256/157472004-d99f5673-9777-4f3d-abc0-3452c2e5fcda.png)

**Comment by johanfrick** [comment]
@cgeroldinger That's beta then, mute button is not released to non-beta yet :-)

**Comment by johanfrick** [comment]
@cstrand89 Do you agree that it's the picture itself? Then we can close this issue

**Comment by johanfrick** [comment]
> Yes I stupidly didn’t actually try any other channels but having done that I realise it’s the BBC picture that has the corners!

😅
