### ISSUE TITLE
[FR] Ungrouping master

### ISSUE THREAD

**Issue by giuliandenicola1** [johanfrick/custom-sonos-card#38]
Hi, would it be possible to have the master speaker in the ungrouping list? 

**For example:** When I'm in my bedroom listening to music and I group my livingroom then when I move there I cannot ungroup my bedroom.

Greetings.

**Comment by johanfrick** [comment]
Fixed here https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.2.2
