### ISSUE TITLE
[Question] Icon / Logo

### ISSUE THREAD

**Issue by giuliandenicola1** [johanfrick/custom-sonos-card#39]
Hi, I'm wondering if you can change the background images of the media browser from sonos and spotify (`..ant.io/_/sonos/logo.png`) to (`..ant.io/_/sonos/icon.png`) like in the official media browser.

Logo
<img width="428" alt="Schermafbeelding 2022-03-09 om 21 48 03" src="https://user-images.githubusercontent.com/67443916/157533814-3651221c-9f99-47fe-a04d-dd9617be32a6.png">
<img width="428" alt="Schermafbeelding 2022-03-09 om 21 56 47" src="https://user-images.githubusercontent.com/67443916/157534648-bdbd4628-aead-45c6-b48e-fc7ce1cf1731.png">

Icon
<img width="428" alt="Schermafbeelding 2022-03-09 om 21 49 31" src="https://user-images.githubusercontent.com/67443916/157533797-abf7ee6d-44af-4c1f-8a2a-166f90be5e9c.png">
<img width="428" alt="Schermafbeelding 2022-03-09 om 21 56 37" src="https://user-images.githubusercontent.com/67443916/157534663-5a1abb5e-50e1-4593-8116-0eadea253478.png">

On a dark theme the black sonos logo is almost like an empty tile.
Greetings.

**Comment by johanfrick** [comment]
Thanks for finding this :-) 
Fixed by https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.2.3

The rule is pretty strict in code now, so it might stop working when Home Assistant change their urls:
```js
thumbnail = thumbnail?.match(/https:\/\/brands.home-assistant.io\/.+\/logo.png/)
      ? thumbnail?.replace('logo.png', 'icon.png')
      : thumbnail;
```

**Comment by giuliandenicola1** [comment]
Nice!

> The rule is pretty strict in code now, so it might stop working when Home Assistant change their urls:

Won't it be possible to have it revert back to the original code when not finding any match?

**Comment by johanfrick** [comment]
That's what the code does

**Comment by giuliandenicola1** [comment]
Sorry, then I do not understand what will break if home assistant changes it's code?

**Comment by johanfrick** [comment]
if they change their icon url to something else, it will break. 
I look for logo.png, and replace with icon.png. But if they change it to something else than icon.png it won't work anymore.

**Comment by giuliandenicola1** [comment]
Ah ok I understand!

What I meant was before simply said it was just a single line code (``${this.mediaItem.thumbnail ? `background-image: url(${this.mediaItem.thumbnail});` : ''};``) right? 
Now it will check if there is a URL with logo.png or icon.png isn't it possible to simply said have it if both fails that it will go back to that single line code where logo.png or icon.png is not defined. 

Or is logo.png still defined in that single line code?

**Comment by johanfrick** [comment]
Well... that's a bit more complicated I would guess. We would need to validate the url before actually setting it in the style 🤔
