### ISSUE TITLE
Config Entry for Sonos player to navigate to particular Sonos player

### ISSUE THREAD

**Issue by thewazz1** [johanfrick/custom-sonos-card#40]
I know that currently to navigate to a particular Sonos player you can use #media_player.sonos_player, however, this does not play well with trying to have a particular Sonos show up in line within a particular view in certain dashboards, in this case HomeKit Infused.  I was wondering if there is a way to be able to specify this also with a config entry for the card, such as default_player or target_player?  Thanks.

**Comment by johanfrick** [comment]
https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.4.0

You can now configure `selectedPlayer` (https://github.com/johanfrick/custom-sonos-card#usage)

**Comment by thewazz1** [comment]
Works great... thank you!

**Comment by johanfrick** [comment]
👍
