### ISSUE TITLE
hello would it be possible to add button of tv mode so that after playing music you can click on the tv button to get sound tv via the sonos card?

### ISSUE THREAD

**Issue by jrspowers** [johanfrick/custom-sonos-card#42]

**Comment by johanfrick** [comment]
Sure, I added something here: https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.5.0
Checkout the readme on how to use it (customSources)

**Comment by giuliandenicola1** [comment]
Nicee work @johanfrick ! 

I did find that if you have the media player with the custom source as master then you have the custom buttons but not if you group from another media player

For example I’m listening to music on my couch and having it grouped with my table, I can switch to “TV mode”

But if I’m listening to music on my table and group it with my couch I cannot go into “TV mode”

Hope this helps.

**Comment by johanfrick** [comment]
That sounds tricky to solve 🙂

**Comment by giuliandenicola1** [comment]
Thinking out loud here: Maybe if you base it on groups? So if the media player exists in the group then it will add to the list?

**Comment by giuliandenicola1** [comment]
Yes, you’re right. I was testing it for a bit and even if you do it in the sonos app it will switch to make the TV speakers master. 

https://user-images.githubusercontent.com/67443916/157563957-2d3ad4c5-69de-454a-8674-d150432c229b.MOV

Maybe if possible to switch master within code only if the source button “TV” is pressed?

**Comment by jrspowers** [comment]
@johanfrick can't get the TV customsources not in order?

**Comment by johanfrick** [comment]
@giuliandenicola1 @jrspowers 

This is the best I can come up with at the moment. Please try it out with this beta: https://github.com/johanfrick/custom-sonos-card/releases/tag/v4.0.2
Is it good enough? Seems a bit glitchy sometimes about showing the correct groups.

---
PunxaPhil - I like [coffee](https://www.buymeacoffee.com/punxaphil) 🙂
