### ISSUE TITLE
Fixed volume devices show incorrectly as double 100%

### ISSUE THREAD

**Issue by robchandhok** [johanfrick/custom-sonos-card#45]
**Checklist:**

- [X ] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
3.5.1

**Last working release (if known):**

**Browser and Operating System:**
Chrome 100.0.4896.20, MacOS

**Description of problem:**

For a Sonos device with fixed volume, the percentage is displayed incorrectly (twice 100%) as shown in screenshot.  This is a sonos AMP that shows "FIXED VOLUME" in the Sonos App.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
<img width="676" alt="display_glitch_fixed_volume" src="https://user-images.githubusercontent.com/10090570/157721999-c2861f79-7853-4e01-8ca0-58a399c0e1cc.png">

**Comment by johanfrick** [comment]
Fixed: https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.5.4
