### ISSUE TITLE
ALL slider incorrectly reflects status of anchor device (mute and volume)

### ISSUE THREAD

**Issue by robchandhok** [johanfrick/custom-sonos-card#46]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
3.5.1

**Last working release (if known):**

**Browser and Operating System:**
Chrome 100.0.4896.20, MacOS

**Description of problem:**
When you are in the panel showing the volume sliders (etc.) for all Sonos devices, and you mute or change the volume of the "root" Sonos device for the group, it changes the status for "ALL".  For example, if you mute the root device, the ALL shows muted (which really should be reserved for ALL muted).   In the attached screenshot, I would say "ALL" should not show muted.

Less clear is the behavior of the ALL volume slider, but I don't think the Sonos app uses the same value there (some sort of weighted average).

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
<img width="459" alt="Screen Shot 2022-03-10 at 10 40 37 AM" src="https://user-images.githubusercontent.com/10090570/157732522-66bdaab8-14cb-46be-9c59-857899fd07fb.png">

**Comment by johanfrick** [comment]
Fixed: https://github.com/johanfrick/custom-sonos-card/releases/tag/v3.5.3
