### ISSUE TITLE
night sound button

### ISSUE THREAD

**Issue by jrspowers** [johanfrick/custom-sonos-card#50]
hello 

it would be useful if you could add the night sound button so that you can turn it on at night and turn it off while thinking ?

**Comment by jrspowers** [comment]
![image](https://user-images.githubusercontent.com/60328474/158064525-2ee67780-b33a-4f3b-bbd8-891b9ba55f1c.jpeg)

**Comment by johanfrick** [comment]
This will be handled in #59
