### ISSUE TITLE
Use replace instead of replaceAll to increase backward compatibility

### ISSUE THREAD

**Issue by SLAZ666** [johanfrick/custom-sonos-card#52]
**Is your feature request related to a problem? Please describe.**
I'm running Fully Kiosk Browser on an older Tablet with Android 5.1.1. Unfortunately, also the webkit version is on 75.
This version does not implement the **replaceAll** function for strings.

**Describe the solution you'd like**
Replace all **replaceAll** string function calls (appear only on **window.location.href**) with **replace**. As the replace regex allready contains the global flag, this should not break anything. I have only made a quick test and now the site loads correctly, but have not tested the overall functionallity.

**Comment by johanfrick** [comment]
Maybe you can make a pull request?

**Comment by johanfrick** [comment]
@SLAZ666 I have made a beta release, could you try it out? https://github.com/johanfrick/custom-sonos-card/releases/tag/v4.0.1

**Comment by SLAZ666** [comment]
Sorry, had no time to make the pull request earlier and wondered why there is a merge conflict 😖 
Now I see you allready made the changes 😄 Have also tried your version and it works on my devices 👍

**Comment by johanfrick** [comment]
😁
Great that it works!
