### ISSUE TITLE
Set the background color in the dashboard yaml file?

### ISSUE THREAD

**Issue by robbinonline** [johanfrick/custom-sonos-card#58]
Would it be possible to set the background / color settings in the dashboard yaml file instead in a theme?

**Comment by johanfrick** [comment]
Working on it, please try the latest beta and let me know how it works

**Comment by robbinonline** [comment]
Awesome, the style can directly placed under type? Like this

- type: custom:custom-sonos-card
   styles:

**Comment by johanfrick** [comment]
https://github.com/johanfrick/custom-sonos-card/blob/stylable/README.md#css-styling
