### ISSUE TITLE
Add Crossfade Button to Control Panel

### ISSUE THREAD

**Issue by SergeantPup** [johanfrick/custom-sonos-card#59]
**Is your feature request related to a problem? Please describe.**
Add a crossfade toggle to the SONOS control panel.

**Describe the solution you'd like**
I would place the crossfade button between the current repeat button and volume up button.  It only needs to be on/off.  The SONOS app uses a bowtie icon and there's a dot under it when on.  I guess a bowtie is as good of icon to indicate crossfade as any.

**Describe alternatives you've considered**
This must be done via the SONOS desktop/mobile application.  There's likely scripts that can be ran in HA to do this.  A button/indicator in the SONOS card is most appropriate.

**Additional context**
<img width="302" alt="2022-04-06 16_57_33-Greenshot" src="https://user-images.githubusercontent.com/48838594/162069786-ad88f1e2-1469-4c43-a9fa-e49af51d1c2b.png">

**Comment by johanfrick** [comment]
Please try this one: https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.1.0-beta1

This loops through all related switches for the unit and shows them in the player. Using the following HA template: `{{ device_entities(device_id('media_player.matrum')) }}`

Note that the crossfade functionality seems to be a bit shaky in home assistant. The feedback is slow and state doesn't update promptly. At least that's how it is on my setup. This is the same for this card, and other cards with crossfade.

Icon will be whatever is served from the crossfade switch entity.

Crossfade enabled:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/26582898/162472016-a1689311-62c5-4a0c-b00a-6bcb24e21f27.png">

TV player, with more switches visible:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/26582898/162472031-92afa0e1-2da8-48e0-b4a1-70d19e8b2faf.png">

**Comment by jrspowers** [comment]
hello do I have to add this somewhere for the work to be done or does it come in automatically?  HA Template: {{ device_entities(device_id('media_player.matrum')) }} ?

**Comment by johanfrick** [comment]
It’s all automatic 🙂

**Comment by SergeantPup** [comment]
hello, I just downloaded: v5.1.0-beta1 and the new controls work and track correctly.....except for crossfade.  It seems to be hit or miss and was definitely working/reacting/controlling but then it would just stay orange in the UI (but still actually control the cross fade).  I tried to trip up the other buttons and none of them did this.  They all reacted appropriately each time and tracked correctly.

My observations appear isolated to the crossfade button and it doesn't happen every time but at least 50% of the time.

**Comment by johanfrick** [comment]
I know same here. You saw my text above, no?

**Comment by SergeantPup** [comment]
my sincere apologies.  I certainly read it but didn't comprehend it lol

**Comment by johanfrick** [comment]
I’m considering releasing anyway, hoping they’ll fix it server side eventually

**Comment by johanfrick** [comment]
Released.
