### ISSUE TITLE
Media part upgrade

### ISSUE THREAD

**Issue by balintbuzasi** [johanfrick/custom-sonos-card#64]
Is it possible to somehow filter the media displayed in the media browser? e.g. I’d like to skip local media & netatmo

Is it possible to set the default state of media broweser? e.g. I’d like to load my wife’s sono playlists

**Comment by johanfrick** [comment]
Fixed the ignore part in https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.4.0
Example:
```mediaBrowserTitlesToIgnore:
  - Local Media
  - My Bad Playlist```

For default state, please create another issue

**Comment by balintbuzasi** [comment]
Great, thank you!
