### ISSUE TITLE
Blank page under 2022.5.0b4

### ISSUE THREAD

**Issue by millermt** [johanfrick/custom-sonos-card#66]
Seems to be an issue with Sonos card under 2022.5.0b4 as I am getting a blank page on dashboard.  View set to panel and YAML is rendered properly.  Cleared cache restarted browser and still not able to view Sonos card.  Any ideas?

**Comment by SergeantPup** [comment]
yes: https://community.home-assistant.io/t/dashboard-sonos-card/393620/255?u=sergeantpup

I've been seeing this for days and just got to dig in last night to determine it was a real issue for me but I've learned from the discord chat and the sonos lovelace card thread that this was a breaking change introduced by the HA beta.

**Comment by johanfrick** [comment]
@millermt @SergeantPup Please try https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.1.1-beta4 and let me know if it works

**Comment by SergeantPup** [comment]
![2022-05-01 14_15_17-Greenshot](https://user-images.githubusercontent.com/48838594/166159010-a237142b-838b-4eeb-82ff-8ae7810afb9d.png)
I think we got a winner.  Immediately started working

**Comment by millermt** [comment]
Confirmed working again on my side, thanks for the fix!

**Comment by johanfrick** [comment]
Great! Released: https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.1.1
