### ISSUE TITLE
customThumbnailIfMissing: # for the media browser section

### ISSUE THREAD

**Issue by cowboysdude** [johanfrick/custom-sonos-card#67]
That field is not working.  NO matter what you put there it shows nothing.

I'm using the latest stable HA
Home Assistant 2022.4.7

**Comment by johanfrick** [comment]
Please provide your config, screenshot and possibly other info to make it easier to understand what is going wrong for you.

**Comment by cowboysdude** [comment]
My Config....

` type: custom:custom-sonos-card        
        shuffleFavorites: false        
        noMediaText: 'No media selected'
        allVolumesText: 'All volumes'
        entityNameRegexToReplace: 'SONOS ' # Regex pattern to replace parts of the entity names
        entityNameReplacement: ''
        layout:
          mobileThresholdPx: 650
          groups:
            width: 90%
            mobileWidth: 100%
          players:
            width: 60%
            mobileWidth: 100%
          favorites:
            width: 100%
            mobileWidth: 100%
          favorite:
            width: 20%
            mobileWidth: 100%          
        selectedPlayer: media_player.sonos_five
        backgroundBehindButtonSections: false # default is false, which means no background behind the different button sections
        skipAdditionalPlayerSwitches: false
        styles:
          button-section:
            backgroundColor: lightblue
            border: 1px solid orange
            margin: auto
            width: 80% 
            padding: 10px
          ha-card:
            padding: 2rem
            background-size: contain

    #        background-image: >-
    #          url(/local/images/circle.jpg)
          groups:
            order: 0
    #        display: none
          players:
            order: 2
          player-body:
            border: 5px black
            color: rgb(0, 0, 204)
            border-radius: 75
          player-song:
            color: '#005cbb'
          font-family: Times New Roman
          font-weight: 900
          mediaBrowser:
            order: 1 
          title:
            fontSize: 29px
            fontWeight: lighter
            textTransform: uppercase
            color: darkblue
`

![Capture](https://user-images.githubusercontent.com/11013648/167250168-52d276f2-8b5c-4b86-b414-3cc4b7412178.PNG)

**Comment by johanfrick** [comment]
You are missing `customThumbnailIfMissing` in your config. Please check the readme

**Comment by cowboysdude** [comment]
Thank you
