### ISSUE TITLE
Styling.....

### ISSUE THREAD

**Issue by cowboysdude** [johanfrick/custom-sonos-card#69]
Following the instructions for styling do not work.

No matter where you put styling it doesn't change anything.   

Sorry to raise a bug report for this but there doesn't appear to be any help in the forum.

There are 2 people there with the same issue.

Here's a screenshot of current situation and that's after putting 'styling' in my theme as well as directly trying to add it to my config.
Nothing changes.

![Capture](https://user-images.githubusercontent.com/11013648/167251084-8a73db94-e878-49d9-a8ad-0e024606d78e.PNG)

Requesting perhaps an examples..... of where and how to use the styling for this card.  

This is in my themes.yaml file directly from the repository and doesn't do a thing.

  sonos-background-color: rgb(255, 0, 0)
  sonos-ha-card-background-color: rgb(198, 203, 210)
  ha-card-box-shadow: none
  sonos-artist-album-text-color: rgb(198, 203, 210)
  sonos-title-color: rgb(198, 203, 210)
  sonos-color: rgb(198, 203, 210)
  sonos-player-section-background: rgb(32, 33, 36)
  sonos-accent-color: rgb(198, 203, 210)

I choose totally obnoxious colors to see if it was even working...... it's not.

Now trying to get the styling to work my player looks like this....

Trying to achieve a look closer to this......

![00b7335affa8eb94f73874a1e2128968d2bdf5c2](https://user-images.githubusercontent.com/11013648/167251420-f4fb646f-9a79-4122-aaee-49201a37da72.jpeg)

**Comment by johanfrick** [comment]
Not sure I understand. Your screenshot in the first image above certainly does not have default styling, so to me it looks like you’ve succeeded with changing the style.
