### ISSUE TITLE
Card fails to display when Sonos instance is offline. 

### ISSUE THREAD

**Issue by ChirpyTurnip** [johanfrick/custom-sonos-card#7]
Hi,

I initially had trouble getting this card to display and was about to chime in on that ticket, BUT, in triple checking the names of the Sonos media player instances I found that one of them was offline - as a result the card would not display. Once it was back online the card configuration saved and the card displayed as expected. 

As a test however I deliberately took another Sonos offline....just to see what would happen. The answer is 'not much' _until_ you restart HA. At that point the card will not display again. The native Sonos media card for that speak goes into a 'grey' unavailable state, but the custom-sonos-card is just gone. 

When I power on the missing Sonos speaker the HA default media card flips over to a 'blue' available state and the speaker can be controlled....but the custom-sonos-card....well....that's just tapped out and gone home!  ;-p

The expected behaviour (from my perspective) is that the Sonos card:

- Must accept all valid media_player entities (check that the entity name is valid, check that the source integration is Sonos) regardless of whether they are currently online or not. 
- Must display any configured Sonos media-player entities that are on line at time of add/update/start up.
- Should periodically refresh states to see if any missing speakers are back on line.

Aside from the disappearing act this custom is pretty darn cool! I expect that this will shortly replace the default media player card as it is just so much easier to control everything together! Keep up the excellent work. :-)

CP

**Comment by ChirpyTurnip** [comment]
OK....so I see it did eventually show up.....so we half a bug....it should display with _some_ speakers if not all are available...and then the updating bit it already does - so that is great!

**Comment by orestesgaolin** [comment]
I agree that currently it's the best card for Sonos devices. 

I have similar issue of not rendering the card when at least one of the speaker gets lost/disconnected in the app. In other words the speaker is still connected to wifi network but Sonos is not able to find it. It seems to be a common problem with Sonos systems :/

**Comment by ghds514** [comment]
I am experiencing this issue. I intentionally disconnect my outdoor units in the winter and it appears to be causing the card to show up as entirely blank. I have removed those outdoor units for now, but would be interested in a way for the card to, perhaps, show offline speakers as such.
