### ISSUE TITLE
Disabling/personalizing  Dynamic volume level slider fonction

### ISSUE THREAD

**Issue by ALaDoffe** [johanfrick/custom-sonos-card#71]
Hi

I just discovered this very nice card. Thx
Dynamic volume level slider is a good fonction.
Is it a way to configure scale values, color, threshold... ?

For my case i only want to use color maybe 3 colors (green, yellow,red) depending volume.
But I  don't want to use different scale

Regards

**Comment by johanfrick** [comment]
Sounds like a nice feature! Feel free to make a pull request 🙂

**Comment by ALaDoffe** [comment]
I'd like, but unfortunately I don't know how to do. :-)

**Comment by johanfrick** [comment]
You can now use `disableDynamicVolumeSlider: true`

**Comment by ALaDoffe** [comment]
Great! Thank you for your work
