### ISSUE TITLE
Add mediaArtworkOverrides.mediaContentIdEquals

### ISSUE THREAD

**Issue by vbtrek** [johanfrick/custom-sonos-card#72]
Would it be possible to add another property to mediaArtworkOverrides, I would like mediaContentIdEquals, reason being when we play BBC iPlayer sources media_title is blank, but media_content_id is set to a url type string Eg. hls-radio://https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high_secure/cfs/bbc_radio_two.m3u8

**Comment by johanfrick** [comment]
Fixed in https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.5.0
Use `mediaContentIdEquals`
