### ISSUE TITLE
Order Groups

### ISSUE THREAD

**Issue by mperone** [johanfrick/custom-sonos-card#73]
I can't find a way to order groups (the media_player items supplied in the 'entities' setting) other than alphabetically. In my case it makes sense to order them spatially (i.e. the area of the house). Is it possible to specify the order?

If not, perhaps just default to use the order as provided in the entities setting?

**Comment by johanfrick** [comment]
The order of manually provided entities is now respected

**Comment by mperone** [comment]
Looks like with the update to 6.0 this is no longer working?

**Comment by johanfrick** [comment]
Ok, I'll take a look

**Comment by mperone** [comment]
Ah - sorry for the noise! Appreciate the quick response but I diagnosed my own problem. I had the list of entities in the "player" card instead of the "groups" card. It's working perfectly fine.

**Comment by johanfrick** [comment]
Great!
