### ISSUE TITLE
Is it possible to include the radio browser and spotify/local media selector as well?

### ISSUE THREAD

**Issue by chheiss** [johanfrick/custom-sonos-card#76]
I`d like to be able to browse Spotify and the TuneIn Radio stations as well. Can that be added to the media list?

Currently, mine is showing only the favorites selection.

**Comment by johanfrick** [comment]
That is working for other users. Have you working integrations in Home Assistant for Spotify?

**Comment by punxaphil** [comment]
@chheiss You can add custom buttons in the favorites section: https://github.com/punxaphil/custom-sonos-card?tab=readme-ov-file#custom-favorites--sources


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
