### ISSUE TITLE
Unable to ungroup speakers or view favourites

### ISSUE THREAD

**Issue by macbrook98** [johanfrick/custom-sonos-card#77]
I have installed the latest (non beta) version of this today. I am able to play, pause and group speakers but I am unable to ungroup speakers. I click the button to ungroup but nothing happens. I have tried with the standard media card and that ungroups without issue so I do think it is this card causing the issue. I have uninstalled and installed numerous times on different versions but not luck. 

I am also unable to see my favourites or Sonos playlists and couldn't see a guide to configure this. Again, these work fine in the default media card.

**Comment by macbrook98** [comment]
I have today re-installed v5.5.1 and I am still experiencing this issue. I have tried the default HASS media card and this is still working without issue.

Favourites and SONOS are also still missing from the media section.

Thanks @johanfrick

**Comment by johanfrick** [comment]
Any errors in the dev tools console part of the browser?

**Comment by macbrook98** [comment]
When first running the add to group using this card I get the below error:

```
Uncaught (in promise) 
Object { code: "unknown_error", message: "Unknown error" }
​
code: "unknown_error"
​
message: "Unknown error"
​
<prototype>: Object { … }
2
```

After this, I get no errors or actions when I click any ungroup/groups options but also nothing happens from this card. 

I get no errors when using the group/ungroup function on the default media card and it is still able to ungroup speakers after recieving the error from grouping speakers on your sonos card.

Thanks

**Comment by johanfrick** [comment]
"unknown error". That is not too helpful I'm afraid. Let me know if you can get more details to the error.

**Comment by johanfrick** [comment]
Closing until more info is revealed that can help debugging.

**Comment by johanfrick** [comment]
@macbrook98 Could you try this? https://github.com/johanfrick/custom-sonos-card/discussions/239#discussioncomment-7927886

**Comment by johanfrick** [comment]
@macbrook98 I've created a beta release that should hopefully work better, even if you have a player that does not provide favorites (which means you don't need to disable that player)
https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.14.6
Can you please try it out?

**Comment by johanfrick** [comment]
Now only Sonos players are shown: https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.14.7
