### ISSUE TITLE
Use theme colors?

### ISSUE THREAD

**Issue by mbriney** [johanfrick/custom-sonos-card#8]
Finally a useable Sonos interface for HA!  Thank you for all of the hard work on it.

One suggestion, instead of the white cards could you adapt to the theme colors?  I am running a darker theme and the white cards are a bit much on the dark background.

**Comment by Waylikemark** [comment]
Would love this aswell

**Comment by johanfrick** [comment]
Sounds like that would be nice, yes. Can you give any pointers in the code where to add that? And what color variables to use?
Much of this code was not written by me, since I forked the repo.

**Comment by johanfrick** [comment]
Fixed now with https://github.com/johanfrick/custom-sonos-card/releases/tag/v2.0.0

See new section in readme: https://github.com/johanfrick/custom-sonos-card#theme-variables
@Waylikemark @mbriney
