### ISSUE TITLE
Youtube Music artists added into My Sonos fail to display in the media section of the dashboard

### ISSUE THREAD

**Issue by kars85** [johanfrick/custom-sonos-card#81]
**Release with the issue:**
v5.6.0-beta-media_list
**Last working release (if known):**
None
**Browser and Operating System:**
Browser/OS Agnostic - have tried iOS/Firefox on Windows/Chrome/etc...

**Description of problem:**

Youtube Music artists added into My Sonos fail to display under the media section of the dashboard. The only items that I can get to show from Youtube Music are playlists I've created.

**Comment by johanfrick** [comment]
This is not an issue with this card. It’s the same in the home assistant built in media browser. You need to speak with the home assistant team to get this fixed.
