### ISSUE TITLE
 Service 'sonos.join' is deprecated and will be removed in 2022.8, please use 'media_player.join' 

### ISSUE THREAD

**Issue by ALaDoffe** [johanfrick/custom-sonos-card#82]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Latest v5.5.1

**Last working release (if known):**
N/A

**Browser and Operating System:**
Firefox
Safari

**Description of problem:**

Hello,

When joining media players, I get this warning in HA log.
 Service 'sonos.join' is deprecated and will be removed in 2022.8, please use 'media_player.join' 

Regards

**Comment by johanfrick** [comment]
Thanks for reporting!
Fixed in v5.6.0: https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.6.0

---
PunxaPhil - I like [coffee](https://www.buymeacoffee.com/punxaphil) 🙂
