### ISSUE TITLE
Sonos Card breaks native back button

### ISSUE THREAD

**Issue by marcschut002** [johanfrick/custom-sonos-card#87]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
5.7.0

**Last working release (if known):**
?

**Browser and Operating System:**
Safari 15.6 on Macos Monterey AND IOS 15.6 + Home Assistant App

**Description of problem:**
On a dashboard with a Sonos card added the back button doesn't function as it should. 

When I want to use the back button I have to push it 2 times in 1 second or it won't work.
I need the back button on my dashboards for navigating and only with the dashboard with the Sonos card I have this issue.

**Javascript errors shown in the web inspector (if applicable):**
No js errors as far as I can see
```

```

**Additional information:**

**Comment by johanfrick** [comment]
Thanks for reporting it. I will see if I can find a solution for it. The reason is that the selected player is appended in the url, in order to support linking to a specific player.

---
PunxaPhil - I like [coffee](https://www.buymeacoffee.com/punxaphil) 🙂

**Comment by BrianKarlsen** [comment]
I have the same problem with the mushroom chip card's back button. 
Have you faund a fix?
GREAT CARD :)

**Comment by johanfrick** [comment]
@BrianKarlsen @marcschut002 I believe I have fixed it. Can you please try with this beta?
https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.11.0
Let me know if it works!

**Comment by BrianKarlsen** [comment]
Much better!!
But if I add a back button with muchroom chip card I still have to tap a lot off times.
Is that coursed by your card?

**Comment by johanfrick** [comment]
I'm confused! Is it better or not? 😄

**Comment by johanfrick** [comment]
Maybe provide details/screenshots/videos of what is now working better, and what is not working.

**Comment by marcschut002** [comment]
5.11.0 works for me, also with the muchroom back button. Thanks @johanfrick

**Comment by BrianKarlsen** [comment]
@johanfrick Header backbutton works now :) 
@marcschut002 On tablet og pc? My Mushroom back buttons still unstable on tablet but fin on pc

**Comment by marcschut002** [comment]
Tested and works on PC (macOS/safari latest version) and iOS/iPhone (HA app latest version). Could be the javascript cache that should be refreshed? The mushroom back button uses the same js function as the browser back button. If it works for the browser then it should work for the mushroom button also. Can you clear the cache on the tablet HA app and try again?

**Comment by johanfrick** [comment]
Thanks for testing it. It has now been released (non-beta).

[![BMC|85x18, 25%](https://community-assets.home-assistant.io/original/4X/c/b/3/cb32273d8710d5efb2561ef840e68c2fe1b61d52.png) ](https://www.buymeacoffee.com/punxaphil)
