### ISSUE TITLE
Track Progress Bar request

### ISSUE THREAD

**Issue by PRGeno** [johanfrick/custom-sonos-card#88]
**Is your feature request related to a problem? Please describe.**
Not a problem, I love custom-sonos-card as it currently is, but it would be very nice to have the one thing I can find included in the stock media player but not available in the custom card.

**Describe the solution you'd like**
Simply add a track progress bar somewhere in the footer (or anywhere really) of the media player section

**Describe alternatives you've considered**
There doesn't appear to be any alternative available outside of using another media player card

**Additional context**
The stock media player is missing so may of the features the custom-sonos-card has, it would be nice to have something the stock card has that is missing in this custom card.

**Comment by johanfrick** [comment]
@PRGeno Please try this beta: [v5.12.0-track-progress_beta](https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.12.0-track-progress_beta)

**Comment by PRGeno** [comment]
> @PRGeno Please try this beta: [v5.12.0-track-progress_beta](https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.12.0-track-progress_beta)

Well that is exciting to read.  I will give it a go as soon as I can.  However, we currently have house guests for the US Thanksgiving holiday weekend and I have frozen any and all changes to my HA instance to ensure nothing interferes with known operation during this time.  

I will let you know how it goes as soon as I can, if you don't end up releasing this version before I can give it a try.

**Comment by PRGeno** [comment]
It doesn't show up with SiriusXM, which is consistent with other HA media players so I assume the required data isn't supplied by the stream.  But I found other streaming services to be inconsistent with other media players with the bar shown, but not accurate, with the start time starting several seconds ahead (and staying ahead) and the end being sometimes up to hours longer than it should be.  

I rarely use Sons for locally server music files as I find my Squeezebox to be much better when I want to play DJ.  But I also found inaccuracies when I tried playing local tracks.  Again it usually showed tracks starting at 10-12 seconds, instead of 0, and the end time didn't always match.

My tests certainly were not exhaustive, but it appears this feature might be more trouble to implement than it's worth,

**Comment by johanfrick** [comment]
No problem. However, it seems like others are happy with the feature so I'll release it as is.

**Comment by PRGeno** [comment]
Sounds reasonable.  What is the attribute name to turn it off if desired?

**Comment by johanfrick** [comment]
```
styles:
  progress:
    display: none
```
