### ISSUE TITLE
Missing Customizable Styles for Grouping Buttons

### ISSUE THREAD

**Issue by awgneo** [johanfrick/custom-sonos-card#89]
https://github.com/johanfrick/custom-sonos-card/blob/8364ff52da7dbb6694463044a206e0821cfaaad4/src/components/grouping-buttons.ts#L120

Currently, the grouping button's font-size (and icon size) is fixed and cannot be customized via the styles: yaml directive. This is the only fontSize directive missing, I believe. Something like this should be supported:

```
styles:
  member: // or grouping-button, etc
    fontSize: 1.5rem;
```

Perhaps the ha-icon could by dynamically sized as well depending on this value or just keeping it at 0.5rem is fine too.

Thanks!

**Comment by cymone-smart** [comment]
Same issue.

**Comment by johanfrick** [comment]
@awgneo @cymone-smart Please try out this beta: https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.10.0
Example:
```yaml
styles:
  member-name:
    fontSize: 1.5rem
  member-icon:
    fontSize: 0.8rem
```

Let me know if it works for you!

**Comment by johanfrick** [comment]
Thanks for testing it. It has now been released (non-beta).

[![BMC|85x18, 25%](https://community-assets.home-assistant.io/original/4X/c/b/3/cb32273d8710d5efb2561ef840e68c2fe1b61d52.png) ](https://www.buymeacoffee.com/punxaphil)
