### ISSUE TITLE
Music info incorrect

### ISSUE THREAD

**Issue by lloyda** [johanfrick/custom-sonos-card#91]
Most of the time the info displayed for Scala Radio is showing a url.  It sometimes briefly shows the correct information, but most of the time it is wrong.

![image](https://user-images.githubusercontent.com/1671197/191716617-b6c53c86-3f63-4cd5-aeec-e4ed9dd89130.png)

**Comment by johanfrick** [comment]
That is the info I get from Home Assistant. Not sure what to do about it actually?

**Comment by johanfrick** [comment]
No more reports on this, closing it for now
