### ISSUE TITLE
Fix Size for Media Browser

### ISSUE THREAD

**Issue by schmierlappe** [johanfrick/custom-sonos-card#95]
Here a video for my problem. With bigger screens it is not possible to use the media browser with my popup

https://user-images.githubusercontent.com/4019953/202156982-433b2b08-9287-44b9-b1b4-0210de362645.mov

and here the code:

          - type: custom:custom-sonos-card
            singleSectionMode: media browser
            styles:
              ha-card:
                background: none
              group:
                background: none
              title: 
                display: none
              button-section:
                border: none
                background: none
              button-on-section:
                background: none
            layout:
              mobileThresholdPx: 500
              groups:
                width: 20%
                mobileWidth: 80%
              players:
                width: 20%
                mobileWidth: 90%
              mediaBrowser:
                width: 100%
                mobileWidth: 100%
              mediaItem:
                width: 33%
                mobileWidth: 25%
              favorites:
                width: 50%
                mobileWidth: 100%
              favorite:
                width: 15%
                mobileWidth: 25%
            mediaBrowserTitlesToIgnore:
              - Local Media
              - Radio Browser
            card_mod:
              style: |
                ha-card {
                  background: none !important;
                  border: none;
                  box-shadow: none;
                }

description:

As you can see in the video the media items are not always the same size when it is in the folder view the item size is bigger, when I go back to the start view it is smaller. I want it to have all in the same size.

Here some screen from desktop popup, maybe then it is more clear

![image](https://user-images.githubusercontent.com/4019953/202187235-0f0f3e51-858e-412a-a20b-5dfe48c27121.png)

![image](https://user-images.githubusercontent.com/4019953/202187348-2bf7d762-ed7e-4868-af3d-3fa05f2a0a75.png)

And this is happening when I open Spotify Media Browser on Desktop Screen

![image](https://user-images.githubusercontent.com/4019953/202187702-029a1640-e797-450a-8836-f03f2ca42352.png)

**Comment by johanfrick** [comment]
Please add description of problem.
Explain what the issue is, and how things should look/behave.

**Comment by schmierlappe** [comment]
done see above

**Comment by johanfrick** [comment]
I see from your video that it changes, but I fail to see the same behaviour when I try it. Not sure how to reproduce it.
This looks weird to me though:
```
          mediaItem:
            width: 33%
            mobileWidth: 25%
          favorites:
            width: 50%
            mobileWidth: 100%
          favorite:
            width: 15%
            mobileWidth: 25%
```

`favorite` is deprecated. You can remove it. `mediaItem` should be used. 
You can also dig into styling more, and control the layout further with css there.

**Comment by schmierlappe** [comment]
it has to do s.th with my grid. I fixed it now with a fix width on the stack-in-card. I think you can close this one. Sorry for that
