### ISSUE TITLE
Please bring back the media-browser only

### ISSUE THREAD

**Issue by aerozinga** [johanfrick/custom-sonos-card#96]
Issue: In a previous version I could show the media-browser only - now I need to do this in a combination with another card - I dont have the space for that on my dashboard

Proposed Solution: Make the media-browser card "self-sufficient" so that it does not need another card to work

**Comment by johanfrick** [comment]
Thanks for reporting. I’m very surprised it worked before actually. It was never supposed to work without groups.
Good suggestion though, I’ll look into allowing it to work standalone

**Comment by aerozinga** [comment]
Cool thx. :) I could make a really slim design with your media-browser singleSectionMode - this was my config

`      - type: custom:custom-sonos-card
        view_layout:
          grid-area: mb
        singleSectionMode: media browser
        selectedPlayer: media_player.sonos_mancave
        customThumbnailIfMissing:
          Wefunkradio: >-
            https://store-images.s-microsoft.com/image/apps.28723.13510798882838719.4dc3a96b-c2ed-486f-9023-f2731555ff03.bca77d42-53b9-4dc4-86ae-71515b723941?mode=scale&q=90&h=300&w=300
        layout:
          mediaItem:
            width: 25%
            mobileWidth: 25%
        styles:
          button-section:
            background-color: transparent
            border: 0px
            border-width: 0px
          media-button:
            border: 0px
            border-radius: 0px
            background-color: transparent
            background-size: 65%
            background-position: top
          media-button-title:
            background-color: transparent
            height: 90%
            top: 70%
            padding-left: 5px
            padding-right: 5px
            width: 95%
          ha-card:
            padding: 0px
            border: 0px
            font-size: 0px`

**Comment by johanfrick** [comment]
This is fixed now in v5.13.0. You can also use `entityId: media_player.sonos_mancave` if you prefer.

**Comment by aerozinga** [comment]
So awesome - thanks Johan :) Works like a charm - the progress bar is very nice too in the player. Would like to send you a picture of my dashboard but upload doesn't seem to work for me.

**Comment by johanfrick** [comment]
Post in discussions otherwise!
