### ISSUE TITLE
Define amount of Media Browsers Items to show

### ISSUE THREAD

**Issue by schmierlappe** [johanfrick/custom-sonos-card#97]
**Is your feature request related to a problem? Please describe.**
[FR] Define amount of media browser items which should be shown in the card or when to make it scrollable.

**Additional context**

Example: 

Limit to 6 items and then it should scroll

![image](https://user-images.githubusercontent.com/4019953/204026388-98ed1ded-79f1-418b-b03a-2c04161cc7c3.png)

and here a picture how it actually acts

![image](https://user-images.githubusercontent.com/4019953/204026592-6def2cec-f939-4782-895b-56fcbb3630f7.png)

**Comment by johanfrick** [comment]
Hi, and thank you for your feature request. You can solve this already using styles:
```
styles:
  media-buttons:
    maxHeight: 400px;
    overflow: scroll;
```
I understand a limit of items would be even more user friendly, but I don't see a straight forward way to solve it. I'll add it to my todo list, but no promises that I'll build something in the near future.
